<?php
/**
 * footer.phtml
 * Rodapé do layout
 * 
 * @package layouts
 * @author Mauro Ribeiro
 * @since 2011-07-06
 */
?>


<?php $userData = new Zend_Session_Namespace('UserData');?>



<div id="ee-chat"> </div>

<script>
$(function() {
    <?php if (isset($userData->user)) : ?>

    var chat = new EeChat({
        userId : '<?php echo $userData->user->id ?>',
        userName : '<?php echo $userData->user->name ?>',
        companyId : '<?php echo $userData->user->company->id ?>',
        companyName : '<?php echo $userData->user->company->name ?>'
    });


        <?php if (isset($this->company) && $this->company->id != $userData->user->company->id) : ?>
            chat.attend('<?php echo $this->company->id ?>');
        <?php endif; ?>
   
    <?php else : ?>

    var chat = new EeChat({
        userId : '<?php echo 'IP'.str_replace(".", "", $_SERVER["REMOTE_ADDR"]) ?>',
        userName : 'Visitante',
        companyId : 'IP<?php echo str_replace(".", "", $_SERVER["REMOTE_ADDR"]) ?>'
    });


        <?php if (isset($this->company)) : ?>

        chat.attend(<?php echo $this->company->id ?>);

        <?php endif; ?>

    <?php endif ?>

    chat.getOldMessages();

});
</script>

<?php
// -----------------------------------------------------------------------------
// Menu de navegação
// -----------------------------------------------------------------------------
?>
    <div id="navigation_footer">
        <div class="container">
            <menu>
                <li>
                    <a href="http://blog.empreendemia.com.br" target="_blank" class="tip_tool" title="blog da Empreendemia">
                        blog
                    </a>
                </li>
                <li>
                    <a href="http://www.saiadolugar.com.br" target="_blank" class="tip_tool" title="blog Saia do Lugar">
                        Saia do Lugar
                    </a>
                </li>
                <li>
                    <a href="http://www.twitter.com/empreendemia" target="_blank" class="tip_tool" title="twitter da @empreendemia">
                        twitter
                    </a>
                </li>
                <li>
                    <a href="termos/privacidade" class="modal tip_tool" target="_blank" title="Políticas de Privacidade">
                        privacidade
                    </a>
                </li>
                <li>
                    <a href="faq" class="tip_tool" title="perguntas frequentes">
                        faq
                    </a>
                </li>
                <li>
                    <a href="contato" class="tip_tool" title="entre em contato com a Empreendemia">
                        contato
                    </a>
                </li>
                <li>
                    <a href="sala-de-imprensa" class="tip_tool" title="sala de imprensa">
                        sala de imprensa
                    </a>
                </li>
            </menu>
        </div>
    </div><!-- #navigation_footer -->

<?php
// -----------------------------------------------------------------------------
// Assinatura Empreendemia e copyright
// -----------------------------------------------------------------------------
?>
    <div id="footer">
        <div class="container">
            <div class="copyright">&copy; Copyright 2009 - <?php echo date('Y') ?> - Empreendemia, direitos reservados</div>
            <div class="logo"><img src="images/layout/footer-logo.png" /></div>
        </div>
    </div><!-- #footer -->
    
<div id="bottom_footer">
</div>
    
<div id="fb-root"></div>
