<h1 class="h_title h_xxlarge h_border h_blue">Entre em contato conosco!</h1>

<div class="plaintext">
    <h2 class="h_title h_medium h_blue">Contato em geral</h2>

    <p>Em caso de dúvidas, por favor sinta-se a vontade para mandar um e-mail para <a href="mailto:atendimento@empreendemia.com.br">atendimento@empreendemia.com.br</a></p>
    <br />

    <h2 class="h_title h_medium h_blue h_margin">Outros contatos</h2>
    <p><img alt="" src="images/icons/email_16.gif"> <a href="mailto:atendimento@empreendemia.com.br">atendimento@empreendemia.com.br</a></p>
    <p><img alt="" src="images/icons/twitter_16.gif"> <a target="_blank" href="http://www.twitter.com/empreendemia">@empreendemia</a></p>
    <p><img alt="" src="images/icons/skype_16.png"> empreendemia</p>
    <p><img alt="" src="images/icons/msn_16.png"> atendimento@empreendemia.com.br</p>
    <p><img alt="" src="images/icons/gtalk_16.png"> atendimento@empreendemia.com.br</p>

</div>