<style type="text/css">
h2 {
    font-weight:bold;
    font-size: 12pt;
    color: #888;
}
h2 {
    font-weight:bold;
    font-size: 12pt;
    color: #888;
    margin: 40px 0 20px 0;
}
h3 {
    font-size: 10pt;
    margin: 20px 10px;
}
p {
    font-size: 9pt;
    margin: 10px 40px;
}
ul, ol {
    font-size: 9pt;
    margin: 10px 40px;
}
</style>

<script type="text/javascript">
    function toggleDiv(divid){
        var div = document.getElementById(divid);
        div.style.display = div.style.display == 'block' ? 'none' : 'block';
    }
</script>

<div class="Content" id="ContentDiv">
	<h1 class="h_title h_xxlarge h_border h_blue">FAQ - Frequently Asked Questions</h1>
	<br>
	<h2>Dúvidas sobre a rede</h2>
	<div class="FaqItem">
		<h3>
			<a href="javascript:toggleDiv('About1_div');">

				O que é e para que serve o Empreendemia?
			</a>
		</h3>
		<div style="display:none;" class="FaqAnswer" id="About1_div">

			<p>

                            O Empreendemia é um espaço virtual para acelerar o contato entre clientes e fornecedores.
                            <br>
			    O objetivo da rede é facilitar o acesso a clientes e fornecedores em potencial.
						Através das ferramentas interativas, é possível conseguir novos negócios de forma muito
						mais rápida do que outros canais usados para conhecer clientes e fornecedores.</p>


		</div>
	</div>

	<div class="FaqItem">
		<h3>
			<a href="javascript:toggleDiv('About2_div');">

				Ok, me cadastrei. O que eu faço agora?
			</a>
		</h3>
		<div style="display:none;" class="FaqAnswer" id="About2_div">
                    <p>
						Depois de criar seu perfil, vá até a página Minha Empresa e adicione alguns produtos/serviços na sua vitrine.
						<br>
						Assim que seu perfil e a página da empresa estiverem completas, você pode buscar empresas diretamente
						pelo Diretório de Empresas ou usar alguma de nossas Ferramentas para encontrar clientes ou fornecedores.
						<br>
						Encontrando clientes ou fornecedores em potencial, recomendamos enviar uma mensagem se apresentando e
						fazer o pedido de troca de cartões de visitas.
                   </p>
		</div>
	</div>

	<div class="FaqItem">
		<h3>
			<a href="javascript:toggleDiv('About3_div');">

				Como posso vender mais usando o Empreendemia?
			</a>
		</h3>
		<div style="display:none;" class="FaqAnswer" id="About3_div">

				<p>

						A primeira pergunta que você precisa responder é: meu cliente está na rede?
						<br>
						Os setores mais presentes na rede são:
                                </p>

                                <ul class="NoMargin">
						<li type="circle" style="margin-left: 16px" class="NoMargin">Tecnologia da Informação</li>
						<li type="circle" style="margin-left: 16px" class="NoMargin">Assessoria e consultoria empresarial</li>
						<li type="circle" style="margin-left: 16px" class="NoMargin">Publicidade e propaganda</li>
						<li type="circle" style="margin-left: 16px" class="NoMargin">Comércio atacado/varejo</li>
						<li type="circle" style="margin-left: 16px" class="NoMargin">Design</li>
						<br>
						Os estados mais presentes são:
						<li type="circle" style="margin-left: 16px" class="NoMargin">São Paulo</li>
						<li type="circle" style="margin-left: 16px" class="NoMargin">Rio de Janeiro</li>
						<li type="circle" style="margin-left: 16px" class="NoMargin">Minas Gerais</li>
						<li type="circle" style="margin-left: 16px" class="NoMargin">Paraná</li>
						<li type="circle" style="margin-left: 15px" class="NoMargin">Rio Grande do Sul</li>
                               </ul>

                                                <p>
						Quanto mais amplo for seu público-alvo, maior a possibilidade de conhecer clientes pelo Empreendemia.

                                                </p>


		</div>
	</div>
	<h2>Privacidade</h2>
	<div class="FaqItem">
		<h3>
			<a href="javascript:toggleDiv('privacidade1_div');">

				Meu perfil também é visível para pessoas fora da rede?
			</a>
		</h3>
		<div style="display:none;" class="FaqAnswer" id="privacidade1_div">
                    <p>
                        Pessoas de fora da rede conseguem ver sua página, mas não tem acesso aos seus contatos. O mesmo vale para a página da sua empresa.
                    </p>
		</div>
	</div>

	<div class="FaqItem">
		<h3>
			<a href="javascript:toggleDiv('privacidade2_div');">

				As minhas atualizações aparecem para todos o usuários da rede?
			</a>
		</h3>
		<div style="display:none;" class="FaqAnswer" id="privacidade2_div">
                    <p>
						Sim, mas só as pessoas que trocaram cartão de visitas com você que receberão suas atualizações na página inicial.

                                                </p>

		</div>
	</div>

	<div class="FaqItem">
		<h3>
			<a href="javascript:toggleDiv('privacidade3_div');">

				Consigo ver quais foram os visitantes recentes da minha página?
			</a>
		</h3>
		<div style="display:none;" class="FaqAnswer" id="privacidade3_div">

				<p>

						No pacote Premium é enviado um relatório de visitas, mostrando de quais as cidades são os visitantes.
						A lista dos visitantes não é mostrada para preservar a privacidade dos usuários.
                                </p>

		</div>
	</div>

	<div class="FaqItem">
		<h3>
			<a href="javascript:toggleDiv('privacidade4_div');">

				Posso possuir/trabalhar em mais de uma empresa dentro da rede?
			</a>
		</h3>
		<div style="display:none;" class="FaqAnswer" id="privacidade4_div">

                    <p>

						Ainda não, mas está nos nossos planos ter essa possibilidade.
                    </p>

		</div>
	</div>

	<h2>Premium</h2>
	<div class="FaqItem">
		<h3>
			<a href="javascript:toggleDiv('premium1_div');">

				O que é o Empreendemia Premium?
			</a>
		</h3>
		<div style="display:none;" class="FaqAnswer" id="premium1_div">

                    <p>

						O Empreendemia Premium é um pacote de serviços que destaca o perfil da sua empresa dentro da rede e também te auxilia a usar o máximo dos recursos da rede. Ou seja, vender mais.
                                                <br>
						Ele pode ser testado <u>gratuitamente por 15 dias</u> e os valores variam de 40 a 60 reais mensais.
						Como cliente Empreendemia Premium, você usufrui do tempo de Consultoria dos nossos consultores de negócios para otimizar sua participação na rede.
                    </p>
		</div>
	</div>

	<div class="FaqItem">
		<h3>
			<a href="javascript:toggleDiv('premium2_div');">

				Pra que serve?
			</a>
		</h3>
		<div style="display:none;" class="FaqAnswer" id="premium2_div">
                    <p>

						O Empreendemia Premium é a melhor maneira de você fazer novos negócios.
						O perfil da sua empresa se transforma em um site, com mais informações sobre cada produto/serviço, imagens, vídeos e sua própria identidade visual.
						Além, claro, da consultoria fornecida pela Equipe Empreendemia para otimizar o seu uso da rede.
                    </p>
		</div>
	</div>

	<div class="FaqItem">
		<h3>
			<a href="javascript:toggleDiv('premium3_div');">

				Qual a diferença entre o Premium e o gratuito?
			</a>
		</h3>
		<div style="display:none;" class="FaqAnswer" id="premium3_div">
                    <p>
						O diferencial do Perfil Premium é o <b>destaque</b> da sua empresa dentro da rede.
						<br>
						O Premium inclui ferramentas, consultoria e possibilidade de personalização do perfil,
						que torna sua página mais atraente, o que resulta em mais vendas.
                    </p>
		</div>
	</div>

	<div class="FaqItem">
		<h3>
			<a href="javascript:toggleDiv('premium4_div');">

				Para que tipo de empresas o Empreendemia Premium traz mais resultados?
			</a>
		</h3>
		<div style="display:none;" class="FaqAnswer" id="premium4_div">
			<p>
						Para empresas que tenham potenciais clientes dentro da rede e para empresas que precisem de uma página corporativa facilmente personalizável.
                        </p>
		</div>
	</div>

	<div class="FaqItem">
		<h3>
			<a href="javascript:toggleDiv('premium5_div');">

				Quais são os benefícios do Premium para minha empresa?
			</a>
		</h3>
		<div style="display:none;" class="FaqAnswer" id="premium5_div">
			<p>
						a) Página destacada e personalizável: a página Premium não contém publicidade externa e ainda te dá a possibilidade de inserir sua própria identidade visual, mais informações
						e vídeos sobre produtos e serviços da sua empresa. Além disso, com o perfil Premium sua empresa é encontrada mais facilmente nas buscas do Google.
						<br><br>
						b) Destaque para o <a></a><a href="quero-comprar/ofertas">Mural de Ofertas</a>, um espaço em que você pode promover seus produtos e serviços com descontos exclusivos para usuários do Empreendemia. Usuários Premium aparecem melhor colocados na listagem.
						<br><br>
						c) Botão "Pedir Orçamento": cada um dos produtos e serviços cadastrados na sua Vitrine contém um botão "Pedir Orçamento", onde seus potenciais clientes poderão manifestar
						seu interesse por um orçamento e você recebe no seu e-mail os dados de contato do seu potencial cliente.
						<br><br>
						d) Relatórios mensais: Receba relatórios de quem visitou seu perfil, segmentados por cidade.
						<br><br>
						Além disso, com o perfil Premium, a página da sua empresa aparece com maior destaque nas buscas do Google.
            </p>
		</div>
	</div>

	<h2>Usabilidade</h2>
	<div class="FaqItem">
		<h3>
			<a href="javascript:toggleDiv('usabilidade1_div');">

                            Como faço para adicionar alguém como "amigo"?
			</a>
		</h3>
		<div style="display:none;" class="FaqAnswer" id="usabilidade1_div">
			<p>


                                            No Empreendemia o "adicionar como amigo" é a função "trocar cartões" que você pode encontrar, ao entrar no perfil de um outro usuário, no link abaixo da foto.
                        </p>
		</div>
	</div>

        <div class="FaqItem">
		<h3>
			<a href="javascript:toggleDiv('usabilidade2_div');">

                                O que faço para "trocar cartões"?
			</a>
		</h3>
		<div style="display:none;" class="FaqAnswer" id="usabilidade2_div">
			<p>
                                           Quando você estiver visualizando outro perfil, você verá na parte esquerda da página o botão "trocar cartões". Apesar de trocar cartões ser um bom início, é recomendado que se envie uma mensagem para a pessoa ou empresa com a qual você quer conversar - tenha cuidado: sempre personalize suas mensagens, já que a prática do Spam no Empreendemia é bastante condenada.
                        </p>
		</div>
	</div>

        <div class="FaqItem">
		<h3>
			<a href="javascript:toggleDiv('usabilidade3_div');">

                                Como faço para ver o perfil de outras empresas?
			</a>
		</h3>
		<div style="display:none;" class="FaqAnswer" id="usabilidade3_div">
			<p>

                                           Vá para <a></a><a href="lista-de-empresas">diretório de empresas</a>  - aqui você pode encontrar facilmente qualquer empresa do sistema, seja por localização geográfica, ramo de atuação ou palavra-chave. Ou seja, aqui é o lugar pra você achar clientes e fornecedores facilmente pra então entrar em contato. Encontrando a empresa, basta clicar sobre seu nome e seu perfil será mostrado.
                        </p>
		</div>
	</div>

        <div class="FaqItem">
		<h3>
			<a href="javascript:toggleDiv('usabilidade4_div');">

                                Como faço para enviar uma mensagem a outro usuário?
			</a>
		</h3>
		<div style="display:none;" class="FaqAnswer" id="usabilidade4_div">
			<p>
                                            Quando você estiver visualizando outro perfil, você verá na parte esquerda da página o botão "Enviar Mensagem". - <u>só cuidado</u> : sempre personalize suas mensagens, já que a prática do Spam no Empreendemia é bastante condenada.
			</p>
		</div>
	</div>

        <div class="FaqItem">
		<h3>
			<a href="javascript:toggleDiv('usabilidade5_div');">

                                Meus produtos podem ser comprados direto da minha página?
			</a>
		</h3>
		<div style="display:none;" class="FaqAnswer" id="usabilidade5_div">
			<p>
                                            Não. O usuário interessado em seu produto deverá entrar em contato com você por mensagem dentro da rede, email ou telefone.
			</p>
		</div>
	</div>

        <div class="FaqItem">
		<h3>
			<a href="javascript:toggleDiv('usabilidade6_div');">

                                 Como faço para adquirir um produto/serviço que eu tenha interesse?
			</a>
		</h3>
		<div style="display:none;" class="FaqAnswer" id="usabilidade6_div">
			<p>
                                            Entre em contato com a empresa responsável, por mensagem no perfil, email ou telefone.
                        </p>
		</div>
	</div>

        <div class="FaqItem">
		<h3>
			<a href="javascript:toggleDiv('usabilidade8_div');">

                                O que é Mural de Serviços? Como posso utilizá-lo?
			</a>
		</h3>
		<div style="display:none;" class="FaqAnswer" id="usabilidade8_div">
                    <p>
                                O mural de serviços é o lugar onde você faz gratuitamente uma requisição de produto ou serviço, e a Empreendemia fará uma busca por potenciais fornecedores. Se você ou sua empresa tiver interesse em algum dos serviços listados no mural abaixo, solicite o contato de quem fez o pedido.
                                          <br><br>
                                          Para anunciar um serviço basta clicar em "Novo pedido de serviço", colocar informações sobre a sua requisição e clicar em "Enviar Pedido".
                    </p>
		</div>
	</div>

        <div class="FaqItem">
		<h3>
			<a href="javascript:toggleDiv('usabilidade9_div');">

                                O que é Mural de Ofertas? Como posso utilizá-lo?
			</a>
		</h3>
		<div style="display:none;" class="FaqAnswer" id="usabilidade9_div">
			<p>
                                            O mural de ofertas é o lugar onde você pode cadastrar e procurar por ofertas de empresas com descontos exclusivos para usuários Empreendemia.
                                            <br><br>
                                            Para cadastrar uma oferta basta clicar em Cadastrar Oferta, o sistema automaticamente listará seus produtos bastando você escolher um e preencher mais dados com detalhes de sua oferta, tendo isso feito, clique em "Criar oferta" e pronto.
                                            <br><br>
                                            Se você está procurando adquirir um produto/serviço que está sendo visualizado, basta procurar na aba "Destaques" ou se preferir algo mais segmentado, busque na aba "Lista por Categorias". Assim que tiver encontrado o que procura, clique sobre a oferta e uma página com mais detalhes se abrirá para que você possa entrar em contato com o anunciante e fechar negócio.
                                            </p>
		</div>
	</div>


        <div class="FaqItem">
		<h3>
			<a href="javascript:toggleDiv('usabilidade11_div');">

                                Como posso procurar clientes/fornecedores de uma maneira mais segmentada? (ex. por setor, cidade, etc.)
			</a>
		</h3>
		<div style="display:none;" class="FaqAnswer" id="usabilidade11_div">
			<p>
                                            Vá para <a></a><a href="lista-de-empresas">diretório de empresas</a>  - aqui você pode encontrar facilmente qualquer empresa do sistema, seja por localização geográfica, ramo de atuação ou palavra-chave. Ou seja, aqui é o lugar pra você achar clientes e fornecedores facilmente pra então entrar em contato.
                        </p>
		</div>
	</div>

    </div>
