<h1 class="h_title h_xxlarge h_border h_blue">Sala de imprensa</h1>

<div class="plaintext">
    <a href="http://www.happyhourcom.com.br/clientes/empreendemia"><img src="http://www.happyhourcom.com.br/sites/all/themes/happyhour/logo.png" style="float:left; margin-top:-20px;" /></a>

    <span style="float:left; padding-top:45px;">
    <p>A assessoria de imprensa da Empreendemia é feita pela HappyHour Comunicação.</p>
    
    <h2 class="h_title h_medium h_blue h_margin">
         <a href="http://www.happyhourcom.com.br/clientes/empreendemia/imprensa">Press-releases</a> ||
	 <a href="http://www.happyhourcom.com.br/clientes/empreendemia/clipping">Clipping</a> ||
	 <a href="http://www.happyhourcom.com.br/clientes/empreendemia">Outras Informacoes</a>
    </h2>
    </span>
 
    <h2 class="h_title h_medium h_blue h_margin" style="width:100%; display:inline-block; margin-top:20px;margin-bottom:-20px;">Informacoes para a imprensa</h2>
    <p style="width:100%; display:inline-block;">Happy Hour Comunicação | (19)3294-5656 / (19)3325-690 <a href="www.happyhourcom.com.br">www.happyhourcom.com.br</a></p>

    <h2 class="h_title h_medium h_blue h_margin">Jornalistas responsaveis</h2>
    <p>Priscila Moraes | priscila@happyhourcom.com.br | Skype: happyhour.02 | (19)3294-5656</p>
    <p>Carlos E. Moura | carlos@happyhourcom.com.br | Skype: happyhour.carlos | (19)9133-9215</p>
</div>
