<?php
/**
 * forgot-password.php
 * Quando usuário clicou em esqueceu senha
 * 
 * @author Mauro Ribeiro
 * @since 2011-09-09
 */
?>
<div class="plaintext">
    <br />
    <br />
    <h1 class="h_title h_blue h_xxlarge">Você pediu uma nova senha!</h1>

    <p>Uma email foi enviado para <strong><?php echo $this->user->login ?></strong> com instruções de como alterar sua senha.</p>

    <p>Em caso de dúvidas, entre em contato com <a href="mailto:atendimento@empreendemia.com.br">atendimento@empreendemia.com.br</a></p>
    <p>Abraços,<br />Equipe Empreendemia</p>
    <br />
    <br />
</div>