<?php
/**
 * generate-password.php
 * Quando usuário recebeu email de gerar nova senha
 * 
 * @author Mauro Ribeiro
 * @since 2011-09-09
 */
?><div class="plaintext">
    <br />
    <br />
    <h1 class="h_title h_blue h_xxlarge">Senha alterada com sucesso!</h1>

    <p>Sua senha foi alterada com sucesso.</p>

    <p>Você está logado na rede como <strong><?php echo $this->user->login ?></strong>.</p>

    <p><a href="painel/usuario/alterar-senha">Clique aqui</a> para alterar sua senha.</p>

    <br />
    <br />
</div>