<?php
/**
 * logout.php
 * Página quando usuário faz logout
 * 
 * @author Mauro Ribeiro
 * @since 2011-08-31
 */
?>
<div style="text-align:center;margin:20px 0;">

<?php if($this->deleteaccount ) : ?>
    Sua conta foi desativada com sucesso. Para reativa-la basta logar-se novamente.
<?php endif;?>


<script type="text/javascript">
$(function() {
    <?php echo $this->Tracker()->event('User', 'viewed logout ad: printi', $this->user->login, null, true); ?>
})
</script>

<a href="http://www.printi.com.br/#utm_source=Empreendemia&utm_medium=Empreendemia&utm_content=Logout&utm_campaign=Printi%2B1" onclick="<?php echo $this->Tracker()->event('User', 'clicked logout ad: printi', $this->user->login, null, true); ?>">
    <img src="images/ads/logout/printi.png" />
</a>


</div>
