<?php
/**
 * logout.php
 * Página quando usuário faz logout
 * 
 * @author Mauro Ribeiro
 * @since 2011-08-31
 */
?>
<div style="text-align:center;margin:20px 0;">

<?php if($this->deleteaccount ) : ?>
    Sua conta foi desativada com sucesso. Para reativa-la basta logar-se novamente.
<?php endif;?>

<!-- Empreendemia_Logout -->
<div id='div-gpt-ad-1390310404743-0' style='margin:50px auto 50px auto;'>
<script type='text/javascript'>
googletag.cmd.push(function() { googletag.display('div-gpt-ad-1390310404743-0'); });
</script>
</div>

</div>
