<?php
/**
 * card.phtml
 * Email quando usuário recebe pedido de troca de cartão
 * 
 * @author Mauro Ribeiro
 * @since 2011-08-10
 */
require_once APPLICATION_PATH."/views/helpers/Access.php";
?>
<body>
    <div style="display:block;float:left"><a href="<?php echo Zend_View_Helper_Access::autoLoginLink($this->user, 'e/'.$this->from_user->company->slug.'/pessoas/'.$this->from_user->id) ?>"><img src="<?php echo $this->serverUrl().$this->baseUrl().'/'.$this->from_user->imagePath(120) ?>" width="120" height="120" /></a></div>

    <h1 style="display:block;margin:10px 140px;padding-top:10px;"><a href="<?php echo Zend_View_Helper_Access::autoLoginLink($this->user, 'e/'.$this->from_user->company->slug.'/pessoas/'.$this->from_user->id) ?>" style="text-decoration:none"><?php echo $this->from_user->fullName() ?></a></h1>
    <h3 style="display:block;margin:10px 140px;"><a href="<?php echo Zend_View_Helper_Access::autoLoginLink($this->user, 'e/'.$this->from_user->company->slug) ?>" style="text-decoration:none"><?php echo $this->from_user->company->name ?></a></h3>

    <h2 style="display:block;margin:10px 140px;padding-top:20px;"><?php echo $this->from_user->fullName() ?> quer trocar cartões</h2>
    <div style="display:block;margin:10px 140px;"><?php echo nl2br($this->message) ?></div>

    <div style="display:block;margin:20px 140px;padding:10px;background-color:#ccc;color:#fff"><a href="<?php echo Zend_View_Helper_Access::autoLoginLink($this->user, 'painel/usuario/notificacoes') ?>">Clique aqui para aceitar este e outros pedidos de trocas de cartão.</a></div>
</body>