<?php
/**
 * forgot_password.phtml
 * Email quando o cara pediu uma nova senha
 * 
 * @author Mauro Ribeiro
 * @since 2011-09-09
 */
?>
<body>
    <h1 style="display:block;margin:10px;padding-top:10px;">Olá, <a href="<?php echo $this->serverUrl().$this->user->url() ?>" style="text-decoration:none"><?php echo $this->user->fullName() ?></a>!</h1>

    <h2 style="display:block;margin:10px;padding-top:20px;">Você pediu uma nova senha!</h2>
    <div style="display:block;margin:10px;">
        <p>Você solicitou uma nova senha para acessar a empreendemia.</p>
        <p>Se você não fez essa solicitação, favor ignorar este email.</p>

        <br />
        <p>Sua senha será alterada para: <strong><?php echo $this->new_password ?></strong></p>
        <p>Para continuar, clique no link:<br />
            <a href="<?php echo $this->serverUrl() ?><?php echo $this->baseUrl() ?>/gerar-senha/<?php echo $this->user->login ?>/<?php echo $this->hash ?>"><?php echo $this->serverUrl() ?>/gerar-senha/<?php echo $this->user->login ?>/<?php echo $this->hash ?></a>
        </p>


        <br />
        <p>Em caso de dúvidas, entre em contato com <a href="mailto:atendimento@empreendemia.com.br">atendimento@empreendemia.com.br</a></p>
        <p>Abraços,<br />Equipe Empreendemia</p>
    </div>
</body>