<?php
/**
 * welcome.phtml
 * Email de boas vindas
 * 
 * @author Lucas Gaspar
 * @since 2011-05-04
 */
?>
<body>
    <div style="display:block;margin:10px;">
        <p>Olá, <?php echo $this->user->name ?>. Tudo bem?</p>

        <p>Seja bem-vindo(a) ao Empreendemia. Fiquei muito feliz com o seu cadastro e espero que consiga excelentes negócios por aqui!</p>

        <p>Para te ajudar a usar melhor a nossa rede, temos um material muito bacana sobre marketing digital. Te recomendo conferir nosso e-book gratuito chamado "5 passos para vender mais pela internet", com dicas bem práticas para ajudar micro e pequenas empresas que queiram aumentar suas vendas.</p>

        <p>Se você tiver interesse em ver técnicas para conseguir mais negócios pela internet, faça o download do e-book <a href="http://redirect.saiadolugar.com.br/?r=files.saiadolugar.com.br/arquivos/2011/12/Ebook-5-passos-para-vender-mais-pela-internet.pdf">aqui</a>.</p>

        <p>Por curiosidade, como você conheceu o Empreendemia?</p>

        <p>Grande abraço e bons negócios!<br/><br/>
        Millor<br/></p>

    </div>
        <div style="font-family:Verdana,sans-serif;color:#666;text-shadow:1px 1px 0 #fff;font-size:10px;border-top:1px dotted #888;margin-top:20px;margin-bottom:20px">
        <div style="margin-top:20px"><a href="http://www.google.com/url?q=http%3A%2F%2Fempreendemia.com.br%2Fe%2Fempreendemia%2Fpessoas%2F19112010&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNFRecW27X3GEhD-9EoaM0BSO6IfQg" target="_blank"><img style="height:80px;width:80px;float:left" src="http://empreendemia.com.br/userfiles/users/19112/191120103bb9d59a2bf98bf7d8358784b705dc8bd7f19929/200_thumbnail.jpg"></a></div>
        <div style="margin-left:100px;margin-top:20px;color:#0c478b;font-size:20px;font-family:Arial,Helvetica,sans-serif;margin-bottom:2px"><a href="http://www.google.com/url?q=http%3A%2F%2Fempreendemia.com.br%2Fe%2Fempreendemia%2Fpessoas%2F19112010&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNFRecW27X3GEhD-9EoaM0BSO6IfQg" style="color:#0c478b;text-decoration:none" target="_blank">Millor Machado</a></div>
        <div style="margin-left:100px;font-size:12px;font-family:Arial,Helvetica,sans-serif;font-weight:bold;margin-bottom:8px">Diretor de estratégia para a desenrolação do empreendedorismo brasileiro</div>
        <div style="margin-left:100px;margin-bottom:5px">Escritório: (11) 3230-9233</div>
        <div style="margin-top:30px;margin-bottom:5px"><a href="http://www.google.com/url?q=http%3A%2F%2Fwww.empreendemia.com.br&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNEOHUWi5cAicdE_YNDRultw-a6Kaw" style="text-decoration:none;color:#666;font-weight:bold" target="_blank"><img src="http://empreendemia.com.br/images/favicon.ico" style="vertical-align:middle"> empreendemia.com.br</a> - a rede de empresas para acelerar seus negócios</div>
        <div style="margin-bottom:20px"><a href="http://www.google.com/url?q=http%3A%2F%2Fwww.saiadolugar.com.br&amp;sa=D&amp;sntz=1&amp;usg=AFQjCNGESYz86os7gWVbNW448QdbFF-3iA" style="text-decoration:none;color:#666;font-weight:bold" target="_blank"><img src="http://www.saiadolugar.com.br/wp-content/themes/saiadolugar4/images/favicon.ico" style="vertical-align:middle"> saiadolugar.com.br</a> - dicas para o empreendedor que não tem tempo a perder</div>
        <div style="color:#888"><span style="font-style:italic">&quot;Minha vida é um livro abertis!&quot;</span> - Antônio Carlos Bernardes Gomes</div>
    </div></body></html>

    <br />
    <br />
</body>
