<?php
/**
 * welcome.phtml
 * Email de boas vindas
 * 
 * @author Lucas Gaspar
 * @since 2011-05-04
 */
?>
<body>
    <div style="display:block;margin:10px;">
        <p>Olá, <?php echo $this->user->name ?>. Tudo bem?</p>

        <p>Seja bem-vindo(a) ao Empreendemia. Fiquei muito feliz com o seu cadastro e espero que consiga excelentes negócios por aqui!</p>

        <p>Para desenvolver ainda mais seu aprendizado sobre empreendedorismo e gestão, sugerimos conhecer o app <a href="https://go.hotmart.com/L7589083S">12min</a>.</p>

        <p>Eles analisam e sumarizam os principais pontos de livros de negócios e desenvolvimento pessoal. O resultado é um microbook único e otimizado, disponível em áudio e texto, para ser consumido nos pequenos intervalos do dia a dia. Dessa forma você consegue priorizar suas próximas leituras e não deixar o aprendizado para trás mesmo com uma rotina agitada.</p>

        <p><a href="http://hyperurl.co/pdbu9j">Clique aqui para baixar o 12min agora!</a></p>

        <p>Grande abraço e bons negócios!<br/><br/>
        Millor<br/></p>

    </div>

    <br />
    <br />
</body>

