<?php
/**
 * image-update.phtml
 * Atualiza a imagem do usuário
 * 
 * @author Mauro Ribeiro
 * @since 2011-08-01
 */
?>
<?php $this->layout()->setLayout('modal_iframe') ?>
<?php $this->headLink()->appendStylesheet('css/ui/forms.css'); ?>


<?php
// -----------------------------------------------------------------------------
// Formulário
// -----------------------------------------------------------------------------
?>
<?php if ($this->sent) : ?>

<?php $this->modal = null ?>
<?php $this->modal->width = 640 ?>
<?php $this->modal->height = 260 ?>

<div class="plaintext" style="text-align:center;">
<br />

<h1 class="h_title h_blue h_medium">Sua imagem foi atualizada com sucesso!</h1>
<p><?php echo $this->user->imageLink(120) ?></p>
<p><a href="<?php echo $this->user->url() ?>" target="_top">Ver meu perfil</a></p>

</div>

<?php
// -----------------------------------------------------------------------------
// Imagem enviada
// -----------------------------------------------------------------------------
?>
<?php else : ?>

<?php $this->modal = null ?>
<?php $this->modal->width = 640 ?>
<?php $this->modal->height = 240 ?>

<div class="plaintext">
<h1 class="h_title h_blue h_medium">Alterar imagem de usuário</h1>
<p style="font-size:8pt">Você pode enviar arquivos JPG, GIF ou PNG (tamanho máximo de 2MB). Não envie fotos que contenham imagens de personagens de desenho animado, pessoas famosas, nudez, trabalho artístico ou material protegido por direitos autorais. A imagem será recortada automaticamente.</p>
</div>

<div class="form">
<?php echo $this->form ?>
</div>

<div class="clear"></div>

<?php endif ?>