<?php $this->layout()->setLayout('clean') ?>

<div style="width:600px;height:400px;overflow:auto;">


  <p align="center" style="font-weight:bold"><font size="2" face="Calibri"><b>Política de Privacidade
Empreendemia</b></font></p>
<p><font size="2" face="Calibri"> <br>

A privacidade e a segurança das informações cedidas pelos Usuários
da Empreendemia são nossa prioridade. Nosso trabalho tem como objetivo
ganhar e manter sua confiança em nós, usando os melhores recursos
que estejam ao nosso alcance.</font></p>
<p><font size="2" face="Calibri"> <br>
A Empreendemia se reserva o direito de modificar esta Política de Privacidade
a qualquer momento. Todas as modificações serão avisadas através
dos nossos veículos oficiais de comunicação com os Usuários, que
ao permanecerem no sistema demonstram que concordam com as modificações
realizadas.</font></p>
<p><font size="2" face="Calibri"> <br>
A Política de Privacidade trata sobre os seguintes assuntos:</font></p>
<p><font size="2" face="Calibri"> <br>
1- Informações pessoais coletadas pela Empreendemia</font></p>
<p><font size="2" face="Calibri">2- Como a Empreendemia usa as informações
pessoais fornecidas pelos usuários</font></p>
<p><font size="2" face="Calibri">3- O que o usuário pode fazer</font></p>

<p><font size="2" face="Calibri">4- As obrigações do usuário</font></p>
<p><font size="2" face="Calibri">5- Informações importantes</font></p>
<p><font size="2" face="Calibri">6- Segurança</font></p>
<p><font size="2" face="Calibri">7- Contate a Empreendemia para tratar
sobre privacidade</font></p>
<p><font size="2" face="Calibri"> <br>
</font><font size="3" face="Calibri"> <br>
<b>1- Informações pessoais coletadas pela Empreendemia</b></font></p>
<p><font size="2" face="Calibri"> <br>
O objetivo da Empreendemia em permitir que Usuários voluntariamente
coloquem suas informações é facilitar a geração de negócios
entre empresas. A pro-atividade do usuário em nos ceder seus dados
significa que ele quer ser beneficiado com as ferramentas da Empreendemia
e concorda com os termos de privacidade. Caso contrário, o usuário
não deve se tornar membro da Empreendemia.</font></p>

<p><font size="2" face="Calibri"> <br>
<u>Cadastro</u></font></p>
<p><font size="2" face="Calibri">Para se tornar um usuário, o primeiro
passo é o seu cadastro pessoal, onde login, e-mail e senha são
dados obrigatórios, e telefones e descrição são dados optativos.
Para finalizar o cadastro, o usuário deve ou se associar a uma empresa
já cadastrada na Empreendemia, ou criar o perfil de sua empresa, onde
as informações obrigatórias são o nome da empresa, telefone, cidade,
estado, setor, atividade. Website, CNPJ, e-mail, endereço, descrição
e produtos são opcionais.</font></p>
<p><font size="2" face="Calibri"> <br>
As informações adicionais podem ser colocadas tanto durante o cadastro,
quanto num momento posterior de preferência do usuário para alterar
seu perfil pessoal e de sua empresa.  <br>
 <br>
O preenchimento das informações adicionais é de grande importância
para Usuários que queiram receber serviços mais customizados e relevantes,
de acordo com o objetivo da Empreendemia de facilitar negócios entre
empresas.</font></p>
<p><font size="2" face="Calibri"> <br>
<u>Confidencialidade e privacidade das informações</u></font></p>

<p><font size="2" face="Calibri">A Empreendemia se compromete a obedecer
aos seguintes padrões em relação à abertura de cada tipo de informação:</font> <br>
</p>
<p><font size="2" face="Calibri">Informações visíveis para não-usuários
da Empreendemia </font></p>
<ul type="DISC">
  <li><font size="2" face="Calibri">Pessoais: nome, nome da
  empresa, descrição e últimas atualizações públicas. </font></li>
  <li><font size="2" face="Calibri">Da empresa: nome da empresa,
  website, endereço, usuários administradores, usuários participantes,
  descrição, produtos, depoimentos. </font></li>
</ul>
<p><font size="2" face="Calibri">Informações visíveis para usuários
da Empreendemia que não tem contatos com qualquer usuário da sua Empresa</font></p>
<ul type="DISC">

  <li><font size="2" face="Calibri">Pessoais: nome, nome da
  empresa, descrição e últimas atualizações públicas. </font></li>
  <li><font size="2" face="Calibri">Da empresa: nome da empresa,
  website, telefone, e-mail, endereço, usuários administradores, usuários
  participantes, descrição, produtos e depoimentos. </font></li>
</ul>
<p><font size="2" face="Calibri"> <br>
Informações visíveis para os contatos de cada usuário, que não
sejam da mesma empresa</font></p>
<ul type="DISC">
  <li><font size="2" face="Calibri">Pessoais: nome, telefone,
  celular, e-mail, nome da empresa, descrição e últimas atualizações
  públicas e destinadas para sua categoria de contatos. </font></li>
  <li><font size="2" face="Calibri">Da empresa: nome da empresa,
  website, telefone, e-mail, endereço, usuários administradores, usuários
  participantes, descrição, produtos e depoimentos. </font></li>

</ul>
<p><font size="2" face="Calibri"> <br>
Informações visíveis para os contatos de cada usuário, que sejam
da mesma empresa </font></p>
<ul type="DISC">
  <li><font size="2" face="Calibri">Pessoais: nome, telefone,
  celular, e-mail, nome da empresa, descrição e últimas atualizações
  públicas e privadas. </font></li>
  <li><font size="2" face="Calibri">Da empresa: nome da empresa,
  website, telefone, e-mail, endereço, usuários administradores, usuários
  participantes, descrição, produtos e depoimentos. </font></li>
</ul>
<p><font size="2" face="Calibri">Dentre as possibilidades de informações
adicionais, vale reforçar que o CNPJ de cada empresa nunca será
visível para qualquer usuário de outra empresa.</font></p>
<p><font size="2" face="Calibri">A ferramenta Controle de Privacidade
é disponível para pacotes pagos do Empreendemia que especifiquem tal
função. Portanto, para tais casos, o acesso às informações por
qualquer tipo de usuário será de responsabilidade do responsável
pelo perfil.</font></p>

<p><font size="2" face="Calibri">Informações adicionais poderão ser
pedidas ao usuário no caso de um atendimento mais específico por parte
da Empreendemia.</font></p>
<p><font size="2" face="Calibri"><u>Cookies,
Log files, IP e informações sobre o computador</u> </font></p>
<ul type="DISC">
  <li><font size="2" face="Calibri">Cookies são usados para
  identificar o usuário ou visitante do website. </font></li>
  <li><font size="2" face="Calibri">Log files: Todos os usuários
  são rastreados em todas as suas ações. O conteúdo gerado (por exemplo
  mensagens e updates) não são gravados. </font></li>
  <li><font size="2" face="Calibri">IP: Todo usuário é rastreado
  por seu IP. </font></li>
  <li><font size="2" face="Calibri">Informações sobre o computador:
  gravamos dados como navegador, sistema operacional e outras informações
  úteis para levantamento de estatísticas para "debugar" o
  sistema. </font></li>

</ul>
<p><font size="2" face="Calibri"><u>Permissão para a Empreendemia processar
informações sobre o usuário</u></font></p>
<p><font size="2" face="Calibri">As informações cedidas pelos usuários
e registradas devido ao uso do sistema (com exceção ao conteúdo de
mensagens pessoais) servirão como insumos para o mapeamento de informações
de mercado e formação de estatísticas. Através do cadastramento,
uso e fornecimento de informações ao Empreendemia, o usuário deliberadamente
aceita os Termos de Uso e condições da Política de Privacidade sobre
o uso de suas informações.</font></p>
<p><font size="2" face="Calibri">O usuário tem o direito não aceitar
esses termos e proceder com a remoção dos seus dados, assim como explicado
nos Termos de Uso, mas a remoção dos dados não funcionarão de maneira
retroativa, ou seja, as ações anteriores à essa decisão continuarão
armazenados e com uso de acordo com os interesses da Empreendemia.</font></p>
<p><font size="2" face="Calibri"><u>Direito do usuário de acessar,
corrigir e modificar seus próprios dados</u> </font></p>
<p><font size="2" face="Calibri">O usuário tem direito de acessar,
modificar, corrigir e eliminar os dados sobre ele referentes à
sua decisão de ter se tornado um usuário. Se o usuário atualizar
qualquer informação, a Empreendemia poderá manter uma cópia
das informações anteriores fornecidas por ele em nossos arquivos e
documentações sobre uso do sistema. </font></p>
<p><font size="2" face="Calibri"><b> <br>
</b></font><font size="3" face="Calibri"><b>2- Como a Empreendemia
usa as informações pessoais fornecidas pelos usuários</b></font></p>
<p><font size="2" face="Calibri">As informações cedidas pelos usuários
que os tornam pessoalmente identificáveis tem como objetivo fazer com
os usuários se descrevam melhor para os outros. Informações adicionais
coletadas pela Empreendemia através da análise da navegação de cada
usuário e que não o torne identificável pessoalmente (como o padrão
de navegação, por exemplo) são de propriedade exclusiva da Empreendemia,
que pode usar essas informações do modo que melhor julgar apropriada.</font></p>

<p><font size="2" face="Calibri">Além disso, as informações fornecidas
são usadas para: </font></p>
<ul type="DISC">
  <li><font size="2" face="Calibri">Administrar a conta dos
  usuários a fim de customizar cada vez mais os serviços; </font></li>
  <li><font size="2" face="Calibri">Comunicar novidades e atualizações. </font></li>
</ul>
<p><font size="2" face="Calibri">A Empreendemia se compromete a não
vender para informações que tornem os usuários pessoalmente identificáveis
nem seus contatos para terceiros. Porém, a Empreendemia pode retransmitir
mensagens de parceiros (opt-in explicado nos Termos de Uso da Empreendemia).</font></p>
<p><font size="2" face="Calibri">O compartilhamento das informações
dos Usuários com terceiros acontecerá apenas para oferecer os
serviços da Empreendemia (por exemplo, podemos compartilhar as informações
com empresas que farão o sistema de pagamento para alguns serviços
da Empreendemia).  <br>
 <br>
 <br>

</font><font size="3" face="Calibri"><b>3- O que o usuário pode fazer</b></font></p>
<ul type="DISC">
  <li><font size="2" face="Calibri">Revisar, melhorar e alterar
  suas informações tanto pessoais quanto de sua empresa (caso seja administrador
  dela na Empreendemia) através das páginas de perfil. </font></li>
  <li><font size="2" face="Calibri">Escolher quais informações
  pessoais serão visíveis pra as diferentes classificações de contatos<b> </b>
  a partir de 3 de maio de 2010.</font></li>
  <li><font size="2" face="Calibri">Controlar a frequência
  de envio de mensagens da Empreendemia para o seu e-mail pessoal. </font></li>
  <li><font size="2" face="Calibri">Fechar a sua conta na Empreendemia
  mediante pedido aos administradores do site pelo e-mail </font><a target="_blank" href="mailto:atendimento@empreendemia.com.br"><font size="2" face="Calibri" color="#0000FF"><u>atendimento@empreendemia.com.<wbr></wbr>br</u></font></a><font size="2" face="Calibri">.</font></li>

</ul>
<p><font size="2" face="Calibri"> <br>
<b> <br>
</b></font><font size="3" face="Calibri"><b>4- As obrigações do usuário</b></font></p>
<ul type="DISC">
  <li><font size="2" face="Calibri">É dever do usuário obedecer
  aos atuais Termos de Uso e Política de Privacidade, o que inclui respeitar
  propriedade intelectual de terceiros (por exemplo com fotografias). </font></li>
  <li><font size="2" face="Calibri">O usuário não deve executar
  download, upload ou qualquer forma de disseminação de material ou
  informação de caráter violento, ofensivo, racista ou xenofóbico
  ou qualquer um que viole o espírito e objetivos da Empreendemia e sua
  comunidade de usuários. </font></li>
  <li><font size="2" face="Calibri">O usuário não deve prover
  à Empreendemia e/ou a qualquer outro usuário informações que ele
  acredite serem danosas à sua pessoa, profissional ou socialmente. </font></li>

</ul>
<p><font size="2" face="Calibri"> <br>
</font><font size="3" face="Calibri"><b>5- Segurança</b></font></p>
<p><font size="2" face="Calibri">A Empreendemia faz uso de criptografia
de senha e protocolos de confirmação via e-mail para mudanças mais
importantes.</font></p>
<p><font size="2" face="Calibri"> <br>
</font><font size="3" face="Calibri"><b>6- Contate a Empreendemia para
tratar sobre privacidade</b></font><font size="2" face="Calibri">  <br>
Se o usuário tiver qualquer dúvida ou sugestão sobre como a Empreendemia
trabalha com a privacidade das suas informações, o melhor caminho
para isso é através do </font><a target="_blank" href="mailto:privacidade@empreendemia.com.br"><font size="2" face="Calibri" color="#0000FF"><u>privacidade@empreendemia.com.<wbr></wbr>br</u></font></a><font size="2" face="Calibri"> ou também qualquer outro canal de comunicação
da Empreendemia.</font></p>




</div>