<?php $this->layout()->setLayout('clean') ?>

<div style="width:600px;height:400px;overflow:auto;">

<p align="center"><font size="3" ><b>Termos de Uso - Empreendemia</b> </font></p>

<p><font size="3" ><br>
    Estes Termos de Uso aplicam-se ao uso do site e dos serviços oferecidos pela 
    Empreendemia Conteúdo e Publicidade de Internet Ltda - EPP, também denominada 
    Empreendemia daqui em diante. Este site e seus serviços têm por objetivo 
    oferecer a profissionais e empresas um aplicativo online para gerenciar seus 
    contatos e conhecer novos, sempre de maneira interativa através da rede
    social.
</font></p><br>

<p><font size="3" >
    Os Termos de Uso são válidos para quaisquer informações, textos, imagens ou 
    outros materias que sejam colocados (upload), baixados (download) ou que 
    estejam ligados aos serviços oferecidos pela Empreendemia. 
</font></p>

<p><font size="3" ><br>
    A aceitação destes Termos de Uso é totalmente indispensável à utilização 
    do site e seus serviços. Todos os Usuários são informados destes Termos de Uso, 
    os quais deverão ler, certificar-se de tê-los entendidos e aceitar todas as 
    condições neles estabelecidas. Deve ficar claro que a utilização do site 
    implica na aceitação total dos seus Termos de Uso. 
</font></p>

<p><font size="3" ><br>
    O uso dos serviços da Empreendemia também é governado pela
    nossa <b>Política de Privacidade</b>, a qual está incorporada nesse
    Acordo por esta referência e é encontrada no endereço link 
    </font><a href="http://www.empreendemia.com.br/termos/privacidade%20" target="_blank"><font color="#0000FF" size="3" ><u>http://www.empreendemia.com.<WBR>br/termos/privacidade </u></font></a><font size="3" >. 
</font></p>

<p><font size="3" ><br>
    <b>I – OBJETIVO</b> 
</font></p>

<p><font size="3" ><br>
    O site Empreendemia tem como objetivo fornecer um espaço de divulgação para 
    empresas e promover o relacionamento entre clientes, fornecedores e parceiros, 
    sempre com o auxílio do sistema de reputação da rede.
</font></p>

<p><font size="3" ><br>
    As avaliações são feitas exclusivamente pelos usuários diretamente conectados 
    entre si e, por isso, sua veracidade e seu tom estritamente profissional são 
    atributos básicos de boa conduta.
</font></p>
<p><font size="3" ><br>
    Qualquer usuário que aja fora desse escopo definido poderá ser punido 
    com o cancelamento de sua ação pelos administradores do site ou até mesmo 
    com a expulsão da rede.
</font></p>

<p><font size="3" > <br>
    <b>II – CADASTRO</b> 
</font></p>

<p><font size="3" ><br>
    A veracidade dos dados informados no cadastro é responsabilidade do 
    Usuário. Ele deve fazer o preenchimento do cadastro com informações exatas, 
    precisas e verdadeiras, também assume o compromisso de atualizar todos os 
    dados que disponibilizar no site, sempre que houver neles alguma alteração. 
    A Empreendemia se reserva o direito de utilizar todos os meios válidos e 
    possíveis para identificar seus Usuários. 
</font></p>
<p><font size="3" ><br>
    Os Usuários garantem e respondem, em qualquer hipótese, pela veracidade, 
    exatidão e autenticidade dos dados que disponibilizarem no site. A 
    Empreendemia não se responsabiliza pela correção desses Dados inseridos 
    por seus Usuários. Empreendemia também se reserva o direito de solicitar 
    dados adicionais e documentos que entenda serem pertinentes a fim de 
    conferir os dados informados pelo Usuário, assim como inabilitar, 
    temporária ou definitivamente o Usuário que apresentar alguma informação 
    que não seja verdadeira ou que a Empreendemia não conseguir contatar para 
    a verificação dos dados. Ao ser cancelado o cadastro do Usuário, 
    automaticamente será cancelado seu acesso ao uso do site e também a 
    qualquer serviço, não assistindo ao Usuário, por esse motivo, qualquer 
    sorte de indenização ou ressarcimento.
</font></p>

<p><font size="3" > <br>
    <b>III - MANUTENÇÃO DA CONTA DE ACESSO</b> 
</font></p>

<p><font size="3" ><br> 
    O Usuário manterá a senha em sigilo. O Usuário acessará sua conta por meio 
    de seu e-mail e senha, comprometendo-se a não informar a terceiros esses 
    dados, responsabilizando-se integralmente pelo uso que deles seja feito. 
    Compromete-se também a notificar a Empreendemia imediatamente, e através de 
    meio seguro, a respeito de qualquer uso não autorizado de sua conta, bem 
    como o acesso não autorizado por terceiros à mesma. 
</font></p>
<p><font size="3" ><br>
    Caso o Usuário venha a ficar por um período de 6 meses sem movimentar sua 
    conta ou utilizar-se dos serviços oferecidos pela Empreendemia, esta poderá 
    ser imediatamente cancelada com ou sem notificação. 
</font></p>
<p><font size="3" ><br>
    A Empreendemia não pode e não irá se responsabilizar por qualquer perda ou 
    dano causado por falha do usuário em cumprir com os requerimentos acima. 
</font></p>

<p><font size="3" > <br>
    <b>IV - MODIFICAÇÃO DOS TERMOS DE USO</b> 
</font></p>

<p><font size="3" > <br>
    A Empreendemia pode Mudar seus Termos de Uso. A Empreendemia reserva-se o 
    direito de modificar quaisquer dos termos e condições contidas neste Acordo, 
    a qualquer tempo, por meio de atualização do mesmo no site. Estas 
    modificações entrarão em vigor 15 dias após sua publicação no site. 
</font></p>

<p><font size="3" > <br>
    Caso as modificações a serem realizadas neste Termo de Uso não sejam 
    aprovadas pelo Usuário, cabe a ele o direito de recusar as novas condições 
    e rescindir este Termo de Uso no prazo de 10 dias contados da data da 
    publicação referente à modificação. A rescisão deste Termo é feita através 
    da extinção de sua conta de acesso, a ser realizada pelo próprio Usuário. 
</font></p>

<p><font size="3" > <br>
    Na hipótese do Usuário continuar participando do site e serviços da 
    Empreendemia, após 15 dias contados da publicação no site, referente às 
    modificações nos Termos de Uso, isso indicará que ele concordou com todas 
    as modificações comunicadas. 
</font></p>

<p><font size="3" > <br>
    <b>V - RESPONSABILIDADES DO USUÁRIO</b>
</font></p>

<p><font size="3" ><br>
    O usuário declara e garante que todos os conteúdos inseridos por ele na
    Empreendemia: 
</font></p>

<p><font size="3" ><br>
    (i) estão de acordo com todas as leis,
    os estatutos, os decretos e os regulamentos aplicáveis;
</font></p>

<p><font size="3" ><br>
    (ii) não infringem nem infringiram qualquer obrigação ou direito de 
    qualquer pessoa ou entidade incluindo, sem limitação, direitos de 
    propriedade intelectual, publicidade ou privacidade, ou direitos e deveres 
    incluídos no direito do consumidor, responsabilidade do produto, delito ou 
    teorias de contrato; e 
</font></p>

<p><font size="3" ><br>
    (iii) não são pornográficos ou violentos e nem incitam à violência. Não 
    infringir as regras da Empreendemia dispostas neste Termo de uso.
</font></p>

<p><font size="3" ><br>
    São responsabilidades do usuário: 
</font></p>

<p><font size="3" ><br>
    (i) Agir de Acordo com a Moral: 
</font></p>

<ul><p><font size="3" ><br>
    O Usuário compromete-se, em geral, a utilizar o site e seus serviços em 
    conformidade com os presentes Termos de Uso da Empreendemia, com a lei, a 
    moral e os bons costumes aceitos e a ordem pública. 
</font></p></ul>

<p><font size="3" ><br>
    (ii) Não explorar maliciosamente a segurança do sistema: 
</font></p>

<ul><p><font size="3" ><br>
    O Usuário se compromete a utilizar o site e seus serviços de forma adequada 
    e diligente, assim como se abster de utilizá-lo com objetivos ou meios para 
    a prática de atos ilícitos, proibidos pela lei e pelos presentes Termos de 
    Uso, lesivos aos direitos e interesses de terceiros, ou que, de qualquer 
    forma, possa danificar, inutilizar, sobrecarregar ou deteriorar o site e 
    seus serviços, bem como os equipamentos de informática de outros Usuário 
    ou de outros internautas (hardware e software) assim como os documentos, 
    arquivos e toda classe de conteúdos armazenados nos seus equipamentos de 
    informática ou impedir a normal utilização ou gozo do site e seus serviços, 
    equipamentos de informática e documentos, arquivos e conteúdos por parte 
    dos demais Usuários e de outros internautas. 
</font></p></ul>

<p><font size="3" ><br>
    (iii) Manter cópia de dados que julguem importantes: 
</font></p>

<ul><p><font size="3" ><br>
    A Empreendemia é um site para gerenciamento de contatos e pode passar por 
    períodos de manutenção ou mesmo ter alguma perda de dados, assim não é 
    aconselhável que se deposite somente na Empreendemia dados que julguem 
    importante. 
</font></p></ul>

<p><font size="3" ><br>
    (iv) Saber quais materiais postados no site são materiais públicos: 
</font></p>

<ul><p><font size="3" ><br>
    O material, informações e dados inseridos nas comunidades virtuais públicas 
    e nos perfis estão sujeitas a serem inseridas nos mecanismos de busca. Com 
    exceção dos contatos de cada usuário, que só podem ser visualizados pelos 
    membros de sua própria empresa e dados bancários da empresa ou pessoais.    
</font></p></ul>

<p><font size="3" ><br>
    (v) Envio e Recebimento de Arquivos na Empreendemia: 
</font></p>

<ul><p><font size="3" ><br>
    O armazenamento de arquivos é de responsabilidade dos usuários que realizam 
    a operação, e não da Empreendemia. Assim cabe ao usuário verificar se o 
    arquivo solicitado ou enviado contém vírus ou não. E também, verificar se o 
    conteúdo do arquivo corresponde ao que nele é anunciado.
</font></p></ul>

<p><font size="3" ><br>
    (vi) Divulgar, Anunciar ou Veicular MMN (Marketing Multi-Nível): 
</font></p>

<ul><p><font size="3" ><br>
    A Empreendemia não permite qualquer tipo de divulgação de produtos / 
    serviços ou recrutamento de empresas ou pessoas que fazem uso de MMN 
    (Marketing Multi-Nível). Podendo, para isso usar diversas outras 
    comunidades virtuais na Internet própria pra isso.  
</font></p></ul>

<p><font size="3" ><br>
    (vii) Agir de Acordo com os Limites da Liberdade de Expressão: 
</font></p>

<ul><p><font size="3" ><br>
    Dentro da Empreendemia há liberdade de expressão. Porém, deve-se respeitar 
    as pessoas e instituições não agindo de forma a praticar Calúnia, Injúria 
    ou Difamação como descritos nos artigos 138, 139 e 140, respectivamente do 
    Código Penal Brasileiro. Portanto, é proibido ofender ou fazer julgamentos 
    morais a terceiros dentro do site, estando sujeito à exclusão do perfil, 
    como às penalidades previstas na lei pela parte prejudicada.
</font></p></ul>

<ul><p><font size="3" ><br>
    Ao mesmo tempo, é preciso diferenciar o descrito acima do direito do Usuário 
    de expressar descontentamento com outra empresa também inscrita na 
    Empreendemia através de uma avaliação negativa (se existir a conexão entre 
    as duas partes). 
</font></p></ul>

<p><font size="3" ><br>
    (viii) Qualquer negócio feito a partir de contatos feitos através da 
    Empreendemia:
</font></p>

<ul><p><font size="3" ><br>
    É responsabilidade dos usuários todo e qualquer negócio realizado com outros 
    usuários, independente do contato entre as partes ter sido originado na 
    Empreendemia. Por isso, é importante que antes de fechar negócio com 
    qualquer empresa, exista uma maior verificação da outra parte, já que a 
    Empreendemia não tem nenhuma responsabilidade sobre qualquer transação 
    comercial.
</font></p></ul>

<p><font size="3" ><br>
    (ix) Reportar abuso de outros usuários: 
</font></p>

<ul><p><font size="3" ><br>
    É responsabilidade de cada usuário reportar abuso realizado por outro 
    usuário, quando se sentir prejudicado, ameaçado ou ao verificar atividades 
    suspeitas, sempre que fujam das regras determinadas pelos Termos de Uso e 
    Política de Privacidade. O usuário denunciado é passível de exclusão da 
    rede, caso constatado o abuso.
</font></p></ul>

<ul><p><font size="3" ><br>
    A denúncia deve ser feita através do botão “Reportar abuso”, localizado no 
    menu lateral direito no perfil de cada usuário. 
</font></p></ul>

<p><font size="3" ><br>
    (x) Ter 18 anos ou mais:
</font></p>

<ul><p><font size="3" ><br>
        Cada usuário é responsável por suas próprias ações no sistema e, por 
        isso, precisam responder legalmente por elas.
</font></p></ul>

<p><font size="3" ><b><br>
    VI - LINKS
</b></font><br></p>

<p><font size="3" ><br>
    Os serviços da Empreendemia poderão conter links para websites ou fontes 
    terceiros. O usuário está ciente e concorda que a Empreendemia não é 
    responsável por:
</font></p>

<p><font size="3" ><br>
    (i) disponibilidade ou acurácia de tais websites ou fontes; ou 
</font></p>

<p><font size="3" ><br>
    (ii) o conteúdo, os produtos ou serviços disponíveis nesses websites e fontes.
</font></p>

<p><font size="3" ><br>
    Links para tais websites ou fontes não implicam em nenhum aval pela 
    Empreendemia sobre tais ou seus conteúdo, produtos ou serviços disponíveis. 
    O usuário reconhece total responsabilidade sobre isso e assume todos os 
    riscos que possam surgir do uso de tais websites e fontes.
</font></p>

<p><font size="3" ><br><b> 
    VII - DOS DIREITOS AUTORAIS
</b></font></p>

<p><font size="3" ><br>
    O Usuário não deve infringir direitos de terceiros, sobretudo aqueles 
    atinentes aos direitos personalíssimos (incluindo, mas não se limitando a: 
    honra, nome e imagem da pessoa) ou direitos autorais (tais como reproduzir, 
    modificar ou divulgar obra alheia sem expressa autorização do titular). 
</font></p>

<p><font size="3" ><br>
    Os materiais passíveis de proteção autoral são descritos sob a égide da Lei 
    nº. 9.610/98. Em regra, o Usuário é titular dos direitos autorais de toda e 
    qualquer obra que disponibilizar no site, seja na qualidade de autor, 
    detentor de autorização do titular original dos direitos ou ainda como 
    cessionário dos direitos patrimoniais da respectiva obra, salvo quando tal 
    obra estiver consagradamente em domínio público ou sujeita às exceções 
    legais previstas na Lei nº. 9.610/98. 
</font></p>

<p><font size="3" ><br>
    O Usuário, ao aceitar esses Termos de Uso do Empreendemia, autoriza o acesso 
    aos materiais inseridos no site por outros Usuários devidamente cadastrados, 
    além dessas obras estarem sujeitas a serem inseridas em mecanismos de busca, 
    com exceção para as informações colocadas neste Acordo em “RESPONSABILIDADE 
    DO USUÁRIO - Materiais postados no site são materiais públicos”. 
</font></p>

<p><font size="3" ><br>
    O Usuário se responsabiliza pelas obras que inserir na Empreendemia e deverá 
    observar a legislação em vigor, tanto sob o aspecto formal (como a questão 
    dos direitos autorais) quanto para o conteúdo (que não deverá violar as 
    regras positivas nem os bons costumes e os princípios gerais da sociedade).
</font></p>

<p><font size="3" ><br>
    Sendo assim, a Empreendemia não se responsabilizará civil ou penalmente em 
    virtude de eventuais danos, morais ou materiais, causados pelas obras 
    inseridas no site, sejam esses danos causados a outros usuários cadastrados 
    ou a terceiros que porventura não estejam cadastrados como usuários da 
    Empreendemia.
</font></p>

<p><font size="3" ><br>
    O Usuário envolvido em denúncias de irregularidades ou infrações a direitos 
    de terceiros se compromete, portanto, a eximir a Empreendemia de eventuais 
    litígios decorrentes do dano que causou. Caso a Empreendemia seja imputada 
    responsável por quaisquer danos morais ou materiais em virtude de inserção 
    irregular e danos a terceiros, a Empreendemia promoverá ação indenizatória 
    contra o usuário, sendo que este aceita desde já a arcar com todas as custas 
    processuais e honorários advocatícios decorrentes dessa ação judicial. 
</font></p>

<p><font size="3" ><br>
    Através deste acordo, o Usuário mantém seus direitos sobre todo conteúdo 
    que submeter, postar ou mostrar na Empreendemia. Ao submeter, postar ou 
    mostrar conteúdo na Empreendemia, o usuário cede à Empreendemia um licença 
    global, livre do pagamento de royalties (com direto de sublicensiá-la) e 
    não-exclusiva para usar, copiar, reproduzir, processar, adaptar, adaptar, 
    modificar, publicar, transmitir, mostrar e distribuir esse conteúdo em 
    qualquer veículo de mídia ou método de distribuição (conhecido hoje ou que 
    seja desenvolvido no futuro), enquanto o Usuário continuar participando da 
    Empreendemia e seu perfil ativado.
</font></p>

<p><font size="3" ><br>
    O Usuário concorda que a licença inclui o direito para a Empreendemia 
    disponibilizar esse conteúdo para outras empresas, organizações ou 
    indivíduos que fizerem parcerias com a Empreendemia para a transmissão, 
    distribuição ou publicação desse conteúdo em outros veículos de mídia e 
    serviços, sendo estes sujeitos aos nossos termos e condições. Esses usos 
    adicionais sobre o conteúdo podem ser feitos sem compensação financeira. 
</font></p>

<p><font size="3" ><br><b> 
    VIII - O SPAM É PROIBIDO
</b></font></p>

<p><font size="3" ><br>
    O Usuário não usará o site Empreendemia para transmitir, seja direta ou 
    indiretamente, nenhum email em massa nem email comercial não solicitado. 
    Também não usará o site da Empreendemia de nenhuma maneira que viole as 
    Políticas Anti-Spam existentes no país. A sua transgressão constitui uma 
    violação deste Contrato. A Empreendemia pode usar tecnologia de filtragem 
    ou outras medidas para barrar emails em massa e emails comerciais não 
    solicitados e, se o seu uso do site Empreendemia incluir serviços de email 
    relacionados, então, tal tecnologia de filtragem ou outras medidas podem 
    bloquear, seja temporária ou permanentemente, alguns emails enviados ao 
    usuário por meio do site da Empreendemia, até mesmo se tais emails não 
    violarem a Política Anti-Spam. 
</font></p>

<p><font size="3" ><br>
    Os dados, assim como o e-mail dos usuários não serão em hipótese alguma 
    vendidos ou fornecidos a terceiros sem a autorização expressa do mesmo. 
    A Empreendemia pode apenas fazer campanha de e-mail Marketing com parceiros, 
    caso o usuário assinalar que aceita esse tipo de e-mail ao fazer seu 
    cadastro na Empreendemia (opt-in), e essas campanhas estejam de acordo com 
    o ramo profissional do usuário. 
</font></p>

<p><font size="3" > <br><b>
    IX - DIREITO DE PUBLICIDADE 
</b></font></p>

<p><font size="3" ><br>
    A Empreendemia tem total direito a colocar publicidade em todo o site, 
    salvo páginas nas quais acordos sejam feitos com cada Usuário separadamente.
</font></p>

<p><font size="3" ><br>
    O objetivo de mostrar anúncios é prover algo útil para os anunciantes e 
    para os Usuários, já que estes aumentarão a agilidade para que cada Usuário 
    conheça novas empresas com possibilidade de negócios.
</font></p>

<p><font size="3" > <br><b>
    X - COBRANÇA DO SERVIÇO
</b></font></p>

<p><font size="3" ><br>
    O serviço básico oferecido pela Empreendemia de interação com outras 
    empresas é gratuito, mas serviços adicionais tanto da Empreendemia quanto 
    de seus parceiros podem ser cobrados mediante a novo acordo e aviso 
    obrigatório no site. 
</font></p>

<p><font size="3" ><b><br>
    XI – OS PRINCÍPIOS DA EMPREENDEMIA
</b></font></p>

    <font size="3" ><br>
        (i) Os dados de login de Usuários, incluindo seu e-mail e sua senha, 
        jamais serão fornecidos para qualquer terceiro;
    </font>
  
    <font size="3" ><br><br>
        (ii) Somos responsáveis por manter sua senha segura. A senha é 
        armazenada com criptografia de modo que ninguém conseguirá decifrá-la;
    </font>
  
    <font size="3" ><br><br>
        (iii) Integridade, consistência e manutenção dos dados;
    </font>

    <font size="3" ><br><br>
        (iv) Compromisso de atendimento ao cliente.
    </font>

<p><font size="3" > <br> <b>
    XII - CONCORDÂNCIA COM OS TERMOS
</b></font></p>

<p><font size="3" ><br>
    Os Usuários concordam com todos os pontos apresentados nestes Termos de Uso 
    para utilizarem livremente os serviços da Empreendemia.
</font></p>

<p><font size="3" ><b><br>
    XIII - LEGISLAÇÃO APLICÁVEL E FORO DE ELEIÇÃO 
</b></font></p>

<p><font size="3" ><br>
    Os presentes Termos de Uso são regidos pela legislação vigente na República 
    Federativa do Brasil.
</font></p>

<p><font size="3" ><br>
    Fica eleito como foro competente para solucionar eventuais controvérsias 
    decorrentes do presente Termos de Uso o Foro da Comarca de Campinas, Estado 
    de São Paulo. 
</font></p></div>
