<?php
/**
 * add.phtml
 * Adiciona novo produto
 * 
 * @author Mauro Ribeiro
 * @since 2011-08-23
 */
?>
<?php $this->layout()->setLayout('modal_iframe') ?>
<?php $this->headLink()->appendStylesheet('css/ui/forms.css'); ?>
<?php $this->headLink()->appendStylesheet('css/ui/datepicker.css'); ?>
<?php $this->headScript()->appendFile('js/jquery/jquery-ui-1.8.14.full.min.js') ?>
<?php $this->headScript()->appendFile('js/forms/wordcount.js') ?>
<?php $this->headScript()->appendFile('js/forms/ckeditor/ckeditor.js'); ?>

<?php
// -----------------------------------------------------------------------------
// Formulário
// -----------------------------------------------------------------------------
?>
<?php if ($this->sent == false) : ?>


<?php $this->modal = null ?>
<?php $this->modal->width = 600 ?>
<?php $this->modal->height = 400 ?>

<script type="text/javascript">
$(function() {
    $('.datepicker').datepicker({
        dateFormat: 'dd/mm/yy',
        dayNames: ['Domingo', 'Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado'],
        dayNamesMin: ['D', 'S', 'T', 'Q', 'Q', 'S', 'S'],
        dayNamesShort: ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sab'],
        monthNames: ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'],
        monthNamesShort: ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez'],
        prevText: "<<",
        nextText: ">>"
    });

    $('.add_offer').change(function() {
        var checkbox = $(this);
        if (checkbox.is(':checked')) {
            $('.display_offer').slideDown(100);
        }
        else {
            $('.display_offer').slideUp(100);
        }
    });

    $('.add_offer').each(function() {
        var checkbox = $(this);
        if (checkbox.is(':checked')) {
            $('.display_offer').slideDown(100);
        }
        else {
            $('.display_offer').slideUp(100);
        }
    });
});
</script>

<h1 class="h_title h_blue h_medium h_margin">Adicionar produto</h1>

<div class="form">
    <?php echo $this->form ?>
</div>

<?php
// -----------------------------------------------------------------------------
// Produto adicionado
// -----------------------------------------------------------------------------
?>
<?php else : ?>

<?php $this->modal = null ?>
<?php $this->modal->width = 400 ?>
<?php $this->modal->height = 240 ?>
<div class="plaintext">
<h1 class="h_title h_blue h_medium h_margin">Produto adicionado com sucesso!</h1>
<p><a href="<?php echo $this->product->url() ?>" target="_top">Clique aqui</a> para visualizar o produto.</p>
</div>
<?php endif ?>