<?php
/**
 * 2_cols_large_small.phtml
 * Layout com duas colunas, uma larga e uma curta
 * 
 * @package layouts
 * @author Mauro Ribeiro
 * @since 2011-06-29
 */
?><?php $this->headLink()->appendStylesheet('css/cols/large-small.css') ?>
<?php include("elements/head.phtml") ?>

<body>

<div id="body">

    <?php include("elements/user_header.phtml"); ?>

    <?php include("elements/header.phtml"); ?>

    <div id="page">
        <div class="container">
            <?php
            // -----------------------------------------------------------------
            // Primeira coluna (larga)
            // -----------------------------------------------------------------
            ?>
            <div class="col_1">
                <div class="page_header">
                    <h1 class="h_title h_blue h_xxxlarge"><?php echo $this->layout()->header_title ?></h1>
                </div> <!-- .page_header .company_header -->
                <div class="content">
                    <?php echo $this->layout()->content ?>
                </div>
                <div class="clear"></div>
            </div><!-- col_1 -->

            <?php
            // -----------------------------------------------------------------
            // Segunda coluna (pequena)
            // -----------------------------------------------------------------
            ?>
            <div class="col_2">
                <div id="quiz"> </div>
                <?php echo $this->layout()->side ?>
                <div class="clear"></div>
            </div><!-- .col_2 -->

            <div class="clear"></div>
        </div><!-- .container -->
    </div> <!-- #page -->


    <?php include("elements/footer.phtml"); ?>

    <?php
    // -------------------------------------------------------------------------
    // Espaço para segundo footerdo layout
    // -------------------------------------------------------------------------
    ?>
    <div id="content_footer">
        <div class="container">
            
        </div>
    </div><!-- #content_footer -->

</div> <!-- #body -->

<?php include("elements/foot.phtml") ?>
