<?php
/**
 * company.phtml
 * Layout padrão de uma empresa
 * 
 * @package layouts
 * @author Mauro Ribeiro
 * @since 2011-06-20
 */

    if(!isset($this->company)) {
        throw new Exception('VIEW::company not set');
    }

    $this->headLink()->appendStylesheet('css/cols/large-small.css');
    $this->headLink()->appendStylesheet('css/layouts/company.css');
    
    $action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();

    $selected['home'] = '';
    $selected['products'] = '';
    $selected['members'] = '';
    $selected['businesses'] = '';

    if ($action == 'view') $selected['home'] = 'class="selected"';
    if ($action == 'products') $selected['products'] = 'class="selected"';
    if ($action == 'members') $selected['members'] = 'class="selected"';
    if ($action == 'businesses') $selected['businesses'] = 'class="selected"';

?>

<?php include("elements/head.phtml") ?>

    <div id="body">

    <?php include("elements/user_header.phtml"); ?>

    <?php include("elements/header.phtml"); ?>

    <?php if (!$this->company->isPlan('premium')) : ?>
    <div id="top_banner">
        <div id='div-gpt-ad-1376656261904-0' class='banner' style='width:728px; height:90px;'>
        <script type='text/javascript'>
        googletag.cmd.push(function() { googletag.display('div-gpt-ad-1376656261904-0'); });
        </script>
        </div>
    </div>
    <?php endif; ?>
        
    <div id="page">

        <div class="container">
            <?php
            // -----------------------------------------------------------------
            // Primeira coluna (larga)
            // -----------------------------------------------------------------
            ?>
            <div class="col_1">
                <div class="company_header page_header">

                    <h1 id="company_name"><a href="<?php echo $this->company->url() ?>"><?php echo $this->company->name ?></a></h1>

                    <div id="company_thumb"><?php echo $this->company->imageLink(140) ?></div>

                    <?php if($this->company->id != 19112668) :?><div id="company_sector"><a href="lista-de-empresas/<?php echo $this->company->city->region->slug ?>/<?php echo $this->company->city->slug ?>/<?php echo $this->company->sector->slug ?> "><?php echo $this->company->sector->name ?></a> - <a href="lista-de-empresas/<?php echo $this->company->city->region->slug ?>/<?php echo $this->company->city->slug ?>/<?php echo $this->company->sector->slug ?>?s=<?php echo urlencode($this->company->activity) ?>"><?php echo $this->company->activity ?></a></div><?php endif;?>

                    <menu id="company_menu">
                        <li <?php echo $selected['home'] ?>>
                            <a href="<?php echo $this->url(array('company_id'=>$this->company->slug), 'company_view')?>">
                                Principal
                            </a>
                        </li>
                        <li <?php echo $selected['products'] ?>>
                            <a href="<?php echo $this->url(array('company_id'=>$this->company->slug), 'company_products')?>">
                                Produtos
                            </a>
                        </li>
                        <li <?php echo $selected['members'] ?>>
                            <a href="<?php echo $this->url(array('company_id'=>$this->company->slug), 'company_members')?>">
                                Pessoas
                            </a>
                        </li>
                        <li <?php echo $selected['businesses'] ?>>
                            <a href="<?php echo $this->url(array('company_id'=>$this->company->slug), 'company_businesses')?>" class="counter">
                                Avaliações<span class="count"><?php echo $this->count_businesses ?></span>
                            </a>
                        </li>
                    </menu>
                    <?php $userData = new Zend_Session_Namespace('UserData');?>
 
                    <menu id="company_actions_menu">
                        <li>
                            <a href="<?php echo $this->company->url() ?>/pessoas">
                                <img src="images/icons/company_actions_message.gif" />enviar mensagem
                            </a>
                        </li>
                        <?php if(isset($userData->user)) :?>
                        <li>
                            <a href="<?php echo $this->url(array('company_id'=>$this->company->slug), 'company_members')?>">
                                <img src="images/icons/company_actions_cards.gif" />trocar cartões
                            </a>
                        </li>
			<?php endif;?>
                        <li>
                            <a href="<?php echo $this->company->url() ?>/pedir-orcamento" title="Fazer pedido de orçamento" class="tip_tool_top modal_iframe">
                                <img src="images/icons/company_actions_budget.gif" />pedir orçamento
                            </a>
                        </li>
                        <?php if(isset($userData->user)) :?>
                        <li>
                            <a href="<?php echo $this->company->url() ?>/avaliar" title="Avaliar esta empresa" class="modal_iframe tip_tool_top">
                                <img src="images/icons/company_actions_business.gif" />já fiz negócio
                            </a>
                        </li>
                        <?php endif;?>
                    </menu>

                </div> <!-- .page_header .company_header -->
                
                <?php
                // -------------------------------------------------------------
                // Conteúdo da view
                // -------------------------------------------------------------
                ?>
                <div class="content">
                    <?php echo $this->layout()->content ?>
                </div>

                <div class="clear"></div>
            </div><!-- col_1 -->

            <?php
                $premium_style = '';
                if ($this->company->isPlan('premium')) {
                    $premium_style = '
                        <div class="premium_side_image">
                            '.$this->company->premiumSideImage().'
                            <div class="shadow"></div>
                        </div>
                    ';
                }
            ?>

            <?php
            // -----------------------------------------------------------------
            // Segunda coluna - espaço para premium ou anúncios
            // -----------------------------------------------------------------
            ?>
            <div class="col_2">
                <div id="quiz"> </div>
				<?php if ($this->company->isPlan('premium')) : ?>
                <?php echo $premium_style; ?>
                <?php else : ?>
                <div class="ads_display ads_display_lateral ads_display_4"></div>
                <?php endif ?>
            </div><!-- .col_2 -->

            <div class="clear"></div>
        </div><!-- .container -->
    </div> <!-- #page -->

    <?php include("elements/footer.phtml"); ?>
    <?php
    // -------------------------------------------------------------------------
    // Espaço para segundo footer do layout
    // -------------------------------------------------------------------------
    ?>
    <div id="content_footer">
        <div class="container">
            
        </div>
    </div><!-- #content_footer -->        
</div> <!-- #body -->

<?php include("elements/foot.phtml") ?>
