TRUNCATE `empreendemia_dev`.`ads`;
TRUNCATE `empreendemia_dev`.`ads_cities`;
TRUNCATE `empreendemia_dev`.`ads_sectors`;
TRUNCATE `empreendemia_dev`.`budgets`;
TRUNCATE `empreendemia_dev`.`businesses`;
-- TRUNCATE `cities`;
TRUNCATE `empreendemia_dev`.`companies`;
TRUNCATE `empreendemia_dev`.`consultores`;
TRUNCATE `empreendemia_dev`.`contacts`;
-- TRUNCATE `countries`;
TRUNCATE `empreendemia_dev`.`demands`;
TRUNCATE `empreendemia_dev`.`invites`;
TRUNCATE `empreendemia_dev`.`messages`;
TRUNCATE `empreendemia_dev`.`notifies`;
TRUNCATE `empreendemia_dev`.`products`;
-- TRUNCATE `regions`;
-- TRUNCATE `sectors`;
TRUNCATE `empreendemia_dev`.`subscriptions`;
TRUNCATE `empreendemia_dev`.`updates`;
TRUNCATE `empreendemia_dev`.`users`;