<?php
/**
 * updates.phtml
 * Página de novidades da rede do usuário
 * 
 * @author Mauro Ribeiro
 * @since 2011-07-05
 */
?><?php $this->layout()->setLayout('main') ?>
<?php $this->layout()->title = $this->user->name ?>

<?php
// -------------------------------------------------------------------------
// Novidades da empreendemia
// -------------------------------------------------------------------------
?>
<div class="sub_col_1" style="width: 260px">
    <div id="update_news">
        <h1 class="h_title h_small h_grey h_regular">Novidades Empreendemia</h1>
        <h2 class="h_title h_small h_blue">Sistema de chat online!</h2>
        <p>Agora você pode conversar em tempo real com outras empresas do Empreendemia!</p>
        <p>Ao invés de mandar uma mensagem e esperar a pessoa responder, converse na hora com clientes e fornecedores em potencial e acelere seus negócios.</p>
        <p>Veja agora as <a href="lista-de-empresas">empresas que estão online</a>.</p>
    </div>
</div>

<script type="text/javascript">
$(function() {
	$('#message_update_field').each(function() {
		var wordCount = $(this);
		var maxLength = 255;
        var wordCounter = $('#char_counter .counter');

		var length = wordCount.val().length;
		length = maxLength - length;

		if (length < 0) {
			wordCounter.html( '<span style="color:red">' + length + '<span>'  );
		}
		else
			wordCounter.html( length );

		wordCount.keyup(function(){
			var new_length = wordCount.val().length;
			new_length = maxLength - new_length;
			if (new_length < 0) {
				wordCount.val( wordCount.val().substr( 0, maxLength ));
				new_length++;
				wordCounter.html( '<span style="color:red">' + new_length + '<span>'  );
			}
			else
				wordCounter.html( new_length );
		});
	});

    $('#message_update_form').submit(function(e) {
        e.preventDefault();
        $("#updates_list").html('<div class="ajax_loading"><p>recarregando updates</p></div>');
        var form = $(this);
        $.ajax({
           type: "POST",
           url: "novidades/enviar-mensagem",
           data: {
               text: form.find('#message_update_field').val()
           },
           success: function() {
                $("#updates_list").load('updates');
                form.find('#message_update_field').val("");
           }
        });
        return false;
    });
});
</script>
<div class="sub_col_2" style="width: 400px;padding-left:40px;">

    <?php
    // -------------------------------------------------------------------------
    // Últimas avaliações na rede do usuário
    // -------------------------------------------------------------------------
    ?>
    <?php if ($this->businesses) : ?>
    <div class="last_businesses">
        <h1 class="h_title h_small h_blue">Últimas empresas avaliadas</h1>
        <ul>
            <?php $count = 0 ?>
            <?php foreach ($this->businesses as $business) : ?>
            <li <?php if ($count++ == 0) echo 'class="first"' ?>><a href="<?php echo $business->to_company->url() ?>/avaliacoes" class="tip_tool_top" title="<?php echo $business->to_company->name ?>"><?php echo $business->to_company->image(60) ?></a></li>
            <?php endforeach ?>
        </ul>
        <div class="clear"></div>
    </div>
    <?php endif ?>

    <?php
    // -------------------------------------------------------------------------
    // Últimos produtos cadastrados na rede do usuário
    // -------------------------------------------------------------------------
    ?>
    <?php if ($this->products) : ?>
    <div class="last_products">
        <h1 class="h_title h_small h_blue">Últimos produtos cadastrados</h1>
        <ul>
            <?php $count = 0 ?>
            <?php foreach ($this->products as $product) : ?>
            <li <?php if ($count++ == 0) echo 'class="first"' ?>><a href="<?php echo $product->url() ?>" class="tip_tool_top" title="<?php echo $product->name ?>"><?php echo $product->image(60) ?></a></li>
            <?php endforeach ?>
        </ul>
        <div class="clear"></div>
    </div>
    <?php endif ?>

    <?php
    // -------------------------------------------------------------------------
    // Status updates da rede do usuário
    // -------------------------------------------------------------------------
    ?>
    <?php if ($this->contacts) : ?>
    <div id="write_message_update">
        <h1>Enviar mensagem para minha rede</h1>
        <div id="send_message_update">
            <form id="message_update_form">
                <textarea id="message_update_field"></textarea>
                <input id="message_update_submit" type="submit" value="enviar" />
            </form>
            <div id="char_counter"><span class="counter">0</span> caracteres</div>
        </div>
        <div class="clear"></div>
    </div>
    <script type="text/javascript">
        $(function(){
            $("#updates_list").load('updates');
        });

        function updatesPage(number) {
             $("#updates_list_"+number).html('<div class="ajax_loading"><p>carregando página #'+number+'</p></div>');
             $("#updates_list_"+number).load('updates?page='+number);
        }
    </script>

    <div id="updates_list"><div class="ajax_loading"><p>carregando...</p></div></div>
    <?php else : ?>
    <h1 class="h_title h_small h_grey h_regular">Mensagens da minha rede</h1>
    <div class="plaintext">
        <p>Você ainda não tem nenhum contato na rede.</p>
        <p><a href="painel/usuario/convidar">Convide seus contatos</a> para o Empreendemia!</p>
        <p>Para fortalecer sua reputação na rede, você pode convidar seus clientes, fornecedores e parceiros para deixar depoimentos sobre sua empresa.</p>
        <p>Para saber mais, <a href="painel/usuario/convidar">clique aqui</a>.</p>
    </div>
    <?php endif ?>
</div>
<div class="clear"></div>