<style type="text/css">
ul, ol {
    font-size: 9pt;
    margin: 20px 10px;
}

ul li {
    margin: 10px 0;
}

.company {
    height: 100px;
    position: relative;
}

.company .thumb{
    height: 100px;
    width: 100px;
    float: left;
}

.company .name {
    font-size: 16px;
    margin-left: 120px;
    padding-top: 10px;
    margin-bottom: 5px;
    font-weight: bold;
}

.company .description {
    font-size: 14px;
    margin-left: 120px;
    width: 520px;
}
</style>

<script type="text/javascript">
    function toggleDiv(divid){
        var div = document.getElementById(divid);
        div.style.display = div.style.display == 'block' ? 'none' : 'block';
    }
</script>

<div class="Content" id="ContentDiv">
	<h1 class="h_title h_xxlarge h_border h_blue">Empresas de Brindes Corporativos em todo Brasil</h1>

    
        <div class="companies_list">
            <h3 style="font-size:16px;font-weight:bold;color:#280;padding:20px 10px;border-bottom:1px solid #ccc;"><img src="images/icons/user_online.gif" /> Empresas online</h3>
            <ul class="companies">
                <li class="company">
                    <div class="thumb"><a href="http://empreendemia.com.br/e/personalize-impresses" onclick="<?php echo $this->Tracker()->userEvent('exp. brother online v1: comprador escolhe personalize-impresses online', null, true) ?>"><img src="http://empreendemia.com.br/userfiles/companies/19117/19117716c443064503f814a32497e21ee6c9be286ef8b5b8/100_thumbnail.jpg" /></a></div>
                    <h3 class="name"><a href="http://empreendemia.com.br/e/personalize-impresses" onclick="<?php echo $this->Tracker()->userEvent('exp. brother online v1: comprador escolhe personalize-impresses online', null, true) ?>">Personalize Impressões</a> <span style="color:#280;font-size:20px">●</span></h3>
                    <div class="description">Personalize suas impressões em canecas vidro ou porcelana, sacolas retornáveis, camisetas, sandalias havaianas, mouse pad, etc, com a mais nova tendência da atualidade a sublimação digital.</div>
                    <div class="clear"></div>
                </li>
            </ul>
            <h3 style="font-size:16px;font-weight:bold;color:#888;padding:20px 10px;border-bottom:1px solid #ccc;"><img src="images/icons/user_offline.gif" /> Empresas offline</h3>
            <ul class="companies">
                <li class="company">
                    <div class="thumb"><a href="http://empreendemia.com.br/e/brindes-garoto-propaganda" onclick="<?php echo $this->Tracker()->userEvent('exp. brother online v1: comprador escolhe brindes-garoto-propaganda offline', null, true) ?>"><img src="http://empreendemia.com.br/userfiles/companies/19116/19116727efd8f68f0c4ff15e7c478c0f0d5d1c66d380a338/100_thumbnail.png" /></a></div>
                    <h3 class="name"><a href="http://empreendemia.com.br/e/brindes-garoto-propaganda" onclick="<?php echo $this->Tracker()->userEvent('exp. brother online v1: comprador escolhe brindes-garoto-propaganda offline', null, true) ?>">Brindes Garoto Propaganda</a> <span style="color:#800;font-size:20px">●</span></h3>
                    <div class="description">Milhares de opções em Brindes, visite nosso site e conheça nossos produtos. Atendimento, Qualidade e Resultados você encontra aqui. </div>
                    <div class="clear"></div>
                </li>
                <li class="company">
                    <div class="thumb"><a href="http://empreendemia.com.br/e/nukk-conceitos-em-design" onclick="<?php echo $this->Tracker()->userEvent('exp. brother online v1: comprador escolhe nukk-conceitos-em-design offline', null, true) ?>"><img src="http://empreendemia.com.br/userfiles/companies/19123/191233473f664226e7811861074755c7902deafafe57858b/100_c1286f6276.jpg" /></a></div>
                    <h3 class="name"><a href="http://empreendemia.com.br/e/nukk-conceitos-em-design" onclick="<?php echo $this->Tracker()->userEvent('exp. brother online v1: comprador escolhe nukk-conceitos-em-design offline', null, true) ?>">NUKK - Conceitos em Design</a> <span style="color:#800;font-size:20px">●</span></h3>
                    <div class="description">Material promocional e brindes.</div>
                    <div class="clear"></div>
                </li>
                <li class="company">
                    <div class="thumb"><a href="http://empreendemia.com.br/e/a-magia-das-cores-brindes" onclick="<?php echo $this->Tracker()->userEvent('exp. brother online v1: comprador escolhe a-magia-das-cores-brindes offline', null, true) ?>"><img src="http://empreendemia.com.br/userfiles/companies/19122/19122289810ae4ede9a65ac12ee308ac5517e87d208bf8f2/100_a48f6f82ff.jpg" /></a></div>
                    <h3 class="name"><a href="http://empreendemia.com.br/e/a-magia-das-cores-brindes" onclick="<?php echo $this->Tracker()->userEvent('exp. brother online v1: comprador escolhe a-magia-das-cores-brindes offline', null, true) ?>">A Magia Das Cores Brindes</a> <span style="color:#800;font-size:20px">●</span></h3>
                    <div class="description">Venda de Brindes Personalizados</div>
                    <div class="clear"></div>
                </li>
                <li class="company">
                    <div class="thumb"><a href="http://empreendemia.com.br/e/searg-artes-graficas-ltda-epp" onclick="<?php echo $this->Tracker()->userEvent('exp. brother online v1: comprador escolhe searg-artes-graficas-ltda-epp offline', null, true) ?>"><img src="http://empreendemia.com.br/userfiles/companies/19119/19119682dc6342349b5177141dc7252b17fbe008661e8b50/100_thumbnail.jpg" /></a></div>
                    <h3 class="name"><a href="http://empreendemia.com.br/e/searg-artes-graficas-ltda-epp" onclick="<?php echo $this->Tracker()->userEvent('exp. brother online v1: comprador escolhe searg-artes-graficas-ltda-epp offline', null, true) ?>">Searg Artes Graficas Ltda EPP</a> <span style="color:#800;font-size:20px">●</span></h3>
                    <div class="description">Cartões de Visita - Notas Fiscais - Pastas - Adesivos - Folhetos - Catalogos -Imas de Geladeira - Convites Casamento - 15 anos - Bodas - Receituarios Médicos -Folhinhas - Agendas - Canetas</div>
                    <div class="clear"></div>
                </li>
                <li class="company">
                    <div class="thumb"><a href="http://empreendemia.com.br/e/arte-biota" onclick="<?php echo $this->Tracker()->userEvent('exp. brother online v1: comprador escolhe arte-biota offline', null, true) ?>"><img src="http://empreendemia.com.br/userfiles/companies/19118/19118223a8e0d117435f8078545b7ef0d993f919b9712ece/100_thumbnail.png" /></a></div>
                    <h3 class="name"><a href="http://empreendemia.com.br/e/arte-biota" onclick="<?php echo $this->Tracker()->userEvent('exp. brother online v1: comprador escolhe arte-biota offline', null, true) ?>">Arte Biota</a> <span style="color:#800;font-size:20px">●</span></h3>
                    <div class="description">Arte Biota é uma empresa de brindes e soluções em roupas uniformes com material reciclável.Buscamos empresas e pessoas que acreditem no consumo consciente, educaçao ambiental e preservação do meio ambiente</div>
                    <div class="clear"></div>
                </li>
            </ul>
        </div>
    
</div>