<style type="text/css">
ul, ol {
    font-size: 9pt;
    margin: 40px 10px;
}

ul li {
    margin: 20px 0;
}

.company {
    height: 100px;
    position: relative;
}

.company .thumb{
    height: 100px;
    width: 100px;
    float: left;
}

.company .name {
    font-size: 16px;
    margin-left: 120px;
    padding-top: 10px;
    margin-bottom: 5px;
    font-weight: bold;
}

.company .description {
    font-size: 14px;
    margin-left: 120px;
    width: 520px;
}
</style>

<script type="text/javascript">
    function toggleDiv(divid){
        var div = document.getElementById(divid);
        div.style.display = div.style.display == 'block' ? 'none' : 'block';
    }
</script>

<div class="Content" id="ContentDiv">
	<h1 class="h_title h_xxlarge h_border h_blue">Empresas de Contabilidade em Campinas</h1>

    
        <div class="companies_list">
            <ul class="companies">
                <li class="company">
                    <div class="thumb"><a href="http://empreendemia.com.br/e/capital-prime-assessoria-contbil-ss-ltda-19119439"  onclick="<?php echo $this->Tracker()->userEvent('exp. brother online v1: comprador escolhe capital-prime-assessoria-contbil-ss-ltda-19119439 normal', null, true) ?>"><img src="http://empreendemia.com.br/userfiles/companies/19119/19119439cf1a4cf4cae3d8f0bc28d4afd917e336b429261a/100_thumbnail.jpg" /></a></div>
                    <h3 class="name"><a href="http://empreendemia.com.br/e/capital-prime-assessoria-contbil-ss-ltda-19119439" onclick="<?php echo $this->Tracker()->userEvent('exp. brother online v1: comprador escolhe capital-prime-assessoria-contbil-ss-ltda-19119439 normal', null, true) ?>">Capital Prime Assessoria Contábil SS Ltda</a></h3>
                    <div class="description">Escritorio de Assessoria e Contabil situado em Campinas, SP. </div>
                    <div class="clear"></div>
                </li>
                <li class="company">
                    <div class="thumb"><a href="http://empreendemia.com.br/e/jlramos-contabilidade-empresarial" onclick="<?php echo $this->Tracker()->userEvent('exp. brother online v1: comprador escolhe jlramos-contabilidade-empresarial normal', null, true) ?>"><img src="http://empreendemia.com.br/userfiles/companies/19122/19122051b36752c83882e23bda7c4e070d7dbe8fe867839e/100_7f013a0984.jpg" /></a></div>
                    <h3 class="name"><a href="http://empreendemia.com.br/e/jlramos-contabilidade-empresarial" onclick="<?php echo $this->Tracker()->userEvent('exp. brother online v1: comprador escolhe jlramos-contabilidade-empresarial normal', null, true) ?>">JLRamos Contabilidade Empresarial</a></h3>
                    <div class="description">Escritório de Contabilidade, Consultoria e Auditoria, focado em ótima qualidade no atendimento e presteza em suas informações. Fazemos toda rotima contabil, fiscal, DP, Abertura e encerramento.</div>
                    <div class="clear"></div>
                </li>
                <li class="company">
                    <div class="thumb"><a href="http://empreendemia.com.br/e/mts-consultoria-empresarial-ltda" onclick="<?php echo $this->Tracker()->userEvent('exp. brother online v1: comprador escolhe mts-consultoria-empresarial-ltda normal', null, true) ?>"><img src="http://empreendemia.com.br/userfiles/companies/19122/191222463e2444b4c58c96c5bacdcfaa7c143ee9b141c921/100_a34b09bf2e.jpg" /></a></div>
                    <h3 class="name"><a href="http://empreendemia.com.br/e/mts-consultoria-empresarial-ltda" onclick="<?php echo $this->Tracker()->userEvent('exp. brother online v1: comprador escolhe mts-consultoria-empresarial-ltda normal', null, true) ?>">MTS - Consultoria Empresarial LTDA</a></h3>
                    <div class="description">A MTS-Consultoria tornou-se uma empresa de consultoria com soluções estratégicas em Gestão de Empresas, Planejamento Tributário, Contábil, Fiscal, Departamentos Pessoal, Auditoria e Novos Negocios.</div>
                    <div class="clear"></div>
                </li>
                <li class="company">
                    <div class="thumb"><a href="http://empreendemia.com.br/e/knts-auditoria-e-consultoria-ltda" onclick="<?php echo $this->Tracker()->userEvent('exp. brother online v1: comprador escolhe knts-auditoria-e-consultoria-ltda normal', null, true) ?>"><img src="http://empreendemia.com.br/userfiles/companies/19117/19117596e3bc84b778aa513f312ef533656c5961eb25b55a/100_thumbnail.png" /></a></div>
                    <h3 class="name"><a href="http://empreendemia.com.br/e/knts-auditoria-e-consultoria-ltda" onclick="<?php echo $this->Tracker()->userEvent('exp. brother online v1: comprador escolhe knts-auditoria-e-consultoria-ltda normal', null, true) ?>">KNTS- Auditoria e Consultoria Ltda</a></h3>
                    <div class="description">A KNTS oferece serviços de forma personalizada com o mais alto padrão de excelência nas áreas de contabilidade, auditoria, gestão tributária, recursos humanos, finanças corporativas e societária. </div>
                    <div class="clear"></div>
                </li>
                <li class="company">
                    <div class="thumb"><a href="http://empreendemia.com.br/e/mafra-assessoria-contabil-e-empresarial" onclick="<?php echo $this->Tracker()->userEvent('exp. brother online v1: comprador escolhe mafra-assessoria-contabil-e-empresarial normal', null, true) ?>"><img src="http://empreendemia.com.br/userfiles/companies/19115/191154149aef2a227c29b4ccd0f2f1260b8bb62a9b26db03/100_thumbnail.jpg" /></a></div>
                    <h3 class="name"><a href="http://empreendemia.com.br/e/mafra-assessoria-contabil-e-empresarial" onclick="<?php echo $this->Tracker()->userEvent('exp. brother online v1: comprador escolhe mafra-assessoria-contabil-e-empresarial', null, true) ?>">Mafra Assessoria Contábil e Empresarial</a></h3>
                    <div class="description">Consultoria e Assessoria Contábil. Especializado em terceirização Contábil, Planejamento Tributário e Gestão de Recursos Humanos. </div>
                    <div class="clear"></div>
                </li>
                <li class="company">
                    <div class="thumb"><a href="http://empreendemia.com.br/e/vof-consultoria-empresarial-ltda" onclick="<?php echo $this->Tracker()->userEvent('exp. brother online v1: comprador escolhe vof-consultoria-empresarial-ltda normal', null, true) ?>"><img src="http://empreendemia.com.br/userfiles/companies/19116/191165907e820e7d870bb0ac228161b7c3304d7caf1d402b/100_thumbnail.jpg" /></a></div>
                    <h3 class="name"><a href="http://empreendemia.com.br/e/vof-consultoria-empresarial-ltda" onclick="<?php echo $this->Tracker()->userEvent('exp. brother online v1: comprador escolhe vof-consultoria-empresarial-ltda normal', null, true) ?>">Vof Consultoria Empresarial Ltda</a></h3>
                    <div class="description">Descrição da empresa</div>
                    <div class="clear"></div>
                </li>
            </ul>
        </div>
    
</div>