<style type="text/css">
ul, ol {
    font-size: 9pt;
    margin: 20px 10px;
}

ul li {
    margin: 10px 0;
}

.company {
    height: 100px;
    position: relative;
}

.company .thumb{
    height: 100px;
    width: 100px;
    float: left;
}

.company .name {
    font-size: 16px;
    margin-left: 120px;
    padding-top: 10px;
    margin-bottom: 5px;
    font-weight: bold;
}

.company .description {
    font-size: 14px;
    margin-left: 120px;
    width: 520px;
}

.company .button {
    position:relative;
    right:-765px;
    top:-80px;
}
</style>

<script type="text/javascript">
    function toggleDiv(divid){
        var div = document.getElementById(divid);
        div.style.display = div.style.display == 'block' ? 'none' : 'block';
    }
</script>

<div class="Content" id="ContentDiv">
	<h1 class="h_title h_xxlarge h_border h_blue">Empresas de Registro de Patentes</h1>

    
        <div class="companies_list">
            <h3 style="font-size:16px;font-weight:bold;color:#280;padding:20px 10px;border-bottom:1px solid #ccc;"><img src="images/icons/user_online.gif" /> Online</h3>
            <ul class="companies">
                <li class="company">
                    <div class="thumb"><a href="http://www.empreendemia.com.br/e/leal-marcas-e-patentes" onclick="<?php echo $this->Tracker()->userEvent('exp. brother online v1: comprador escolhe leal-marcas-e-patentes online', null, true) ?>"><img src="http://www.empreendemia.com.br/userfiles/companies/19117/1911767303a42cf76fe8d0cab7867b56b71b96778fcd772d/100_c7df37daa2.jpg"/></a></div>
                    <h3 class="name"><a href="http://www.empreendemia.com.br/e/leal-marcas-e-patentes" onclick="<?php echo $this->Tracker()->userEvent('exp. brother online v1: comprador escolhe leal-marcas-e-patentes online', null, true) ?>">Leal Marcas e Patentes</a> </h3>
                    <div class="description"> Marcas e Patentes - Registro Pela Internet Online Pesquisa de Viabilidade de Marca Gratuita Pagamento em até 18 X Sem Juros www.lealmarcasepatentes.com.br </div>
                    <div class="clear"></div>
                    <div class="button"><script src='//d1nu2rn22elx8m.cloudfront.net/buttons/fcdJX/swxWW-NcAfPkquVBu8.js'></script></div>
                </li>
            </ul>
            <div style="font-size:16px;font-weight:bold;color:#888;padding:0 10px;border-bottom:1px solid #ccc;postion:relative;"></div>
            <h3 style="padding: 10px">Para ver a lista de empresas que estão offline, clique <a href="http://empreendemia.com.br/lista-de-empresas?s=Registro+de+Patentes&buscar=buscar">aqui</a>.</h3>
        </div>
    
</div>